-- Add initial data to world database
--
-- We will add player information for default action buttons.
--

-- Select world database
USE `zp_world`;

-- Provide variables for races, and classes
SET @RACE_HUMAN     = 1;
SET @RACE_ORC       = 2;
SET @RACE_DWARF     = 3;
SET @RACE_NIGHT_ELF = 4;
SET @RACE_UNDEAD    = 5;
SET @RACE_TAUREN    = 6;
SET @RACE_GNOME     = 7;
SET @RACE_TROLL     = 8;
SET @RACE_GOBLIN    = 9;

SET @CLASS_WARRIOR  = 1;
SET @CLASS_PALADIN  = 2;
SET @CLASS_HUNTER   = 3;
SET @CLASS_ROGUE    = 4;
SET @CLASS_PRIEST   = 5;
SET @CLASS_SHAMAN   = 7;
SET @CLASS_MAGE     = 8;
SET @CLASS_WARLOCK  = 9;
SET @CLASS_DRUID    = 11;

-- Provide variables for actions, and buttons
SET @ACTION_TYPE_SPELL  = 0;
SET @ACTION_TYPE_MACRO  = 64;
SET @ACTION_TYPE_ITEM   = 128;

-- Insert information for player characters and their default action buttons
INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_HUMAN, @CLASS_WARRIOR, 72, 6603, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_WARRIOR, 73, 78, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_WARRIOR, 83, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_HUMAN, @CLASS_PALADIN, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_PALADIN, 1, 21084, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_PALADIN, 2, 635, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_PALADIN, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_HUMAN, @CLASS_PALADIN, 11, 2070, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_HUMAN, @CLASS_ROGUE, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_ROGUE, 1, 1752, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_ROGUE, 2, 2098, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_ROGUE, 3, 2764, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_ROGUE, 11, 2070, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_HUMAN, @CLASS_PRIEST, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_PRIEST, 1, 585, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_PRIEST, 2, 2050, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_PRIEST, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_HUMAN, @CLASS_PRIEST, 11, 2070, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_HUMAN, @CLASS_MAGE, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_MAGE, 1, 133, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_MAGE, 2, 168, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_MAGE, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_HUMAN, @CLASS_MAGE, 11, 2070, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_HUMAN, @CLASS_WARLOCK, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_WARLOCK, 1, 686, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_WARLOCK, 2, 687, @ACTION_TYPE_SPELL),
    (@RACE_HUMAN, @CLASS_WARLOCK, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_HUMAN, @CLASS_WARLOCK, 11, 4604, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_ORC, @CLASS_WARRIOR, 72, 6603, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_WARRIOR, 73, 78, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_WARRIOR, 74, 20572, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_WARRIOR, 83, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_ORC, @CLASS_HUNTER, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_HUNTER, 1, 2973, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_HUNTER, 2, 75, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_HUNTER, 4, 20572, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_HUNTER, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_ORC, @CLASS_HUNTER, 11, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_ORC, @CLASS_ROGUE, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_ROGUE, 1, 1752, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_ROGUE, 2, 2098, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_ROGUE, 3, 2764, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_ROGUE, 4, 20572, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_ROGUE, 11, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_ORC, @CLASS_SHAMAN, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_SHAMAN, 1, 403, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_SHAMAN, 2, 331, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_SHAMAN, 3, 20572, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_SHAMAN, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_ORC, @CLASS_SHAMAN, 11, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_ORC, @CLASS_WARLOCK, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_WARLOCK, 1, 686, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_WARLOCK, 2, 687, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_WARLOCK, 3, 20572, @ACTION_TYPE_SPELL),
    (@RACE_ORC, @CLASS_WARLOCK, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_ORC, @CLASS_WARLOCK, 11, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_DWARF, @CLASS_WARRIOR, 72, 6603, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_WARRIOR, 73, 78, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_WARRIOR, 74, 20594, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_WARRIOR, 75, 2481, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_WARRIOR, 83, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_DWARF, @CLASS_PALADIN, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_PALADIN, 1, 21084, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_PALADIN, 2, 635, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_PALADIN, 3, 20594, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_PALADIN, 4, 2481, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_PALADIN, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_DWARF, @CLASS_PALADIN, 11, 4540, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_DWARF, @CLASS_HUNTER, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_HUNTER, 1, 2973, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_HUNTER, 2, 75, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_HUNTER, 3, 20594, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_HUNTER, 4, 2481, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_HUNTER, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_DWARF, @CLASS_HUNTER, 11, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_DWARF, @CLASS_ROGUE, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_ROGUE, 1, 1752, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_ROGUE, 2, 2098, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_ROGUE, 3, 2764, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_ROGUE, 4, 20594, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_ROGUE, 5, 2481, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_ROGUE, 11, 4540, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_DWARF, @CLASS_PRIEST, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_PRIEST, 1, 585, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_PRIEST, 2, 2050, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_PRIEST, 3, 20594, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_PRIEST, 4, 2481, @ACTION_TYPE_SPELL),
    (@RACE_DWARF, @CLASS_PRIEST, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_DWARF, @CLASS_PRIEST, 11, 4540, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_NIGHT_ELF, @CLASS_WARRIOR, 72, 6603, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_WARRIOR, 73, 78, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_WARRIOR, 74, 20580, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_WARRIOR, 83, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_NIGHT_ELF, @CLASS_HUNTER, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_HUNTER, 1, 2973, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_HUNTER, 2, 75, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_HUNTER, 3, 20580, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_HUNTER, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_NIGHT_ELF, @CLASS_HUNTER, 11, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_NIGHT_ELF, @CLASS_ROGUE, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_ROGUE, 1, 1752, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_ROGUE, 2, 2098, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_ROGUE, 3, 2764, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_ROGUE, 11, 4540, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_NIGHT_ELF, @CLASS_PRIEST, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_PRIEST, 1, 585, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_PRIEST, 2, 2050, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_PRIEST, 3, 20580, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_PRIEST, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_NIGHT_ELF, @CLASS_PRIEST, 11, 2070, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_NIGHT_ELF, @CLASS_DRUID, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_DRUID, 1, 5176, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_DRUID, 2, 5185, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_DRUID, 3, 20580, @ACTION_TYPE_SPELL),
    (@RACE_NIGHT_ELF, @CLASS_DRUID, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_NIGHT_ELF, @CLASS_DRUID, 11, 4536, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_UNDEAD, @CLASS_WARRIOR, 72, 6603, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_WARRIOR, 73, 78, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_WARRIOR, 74, 20577, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_WARRIOR, 83, 4604, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_UNDEAD, @CLASS_ROGUE, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_ROGUE, 1, 1752, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_ROGUE, 2, 2098, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_ROGUE, 3, 2764, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_ROGUE, 4, 20577, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_ROGUE, 11, 4604, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_UNDEAD, @CLASS_PRIEST, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_PRIEST, 1, 585, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_PRIEST, 2, 2050, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_PRIEST, 3, 20577, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_PRIEST, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_UNDEAD, @CLASS_PRIEST, 11, 4604, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_UNDEAD, @CLASS_MAGE, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_MAGE, 1, 133, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_MAGE, 2, 168, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_MAGE, 3, 20577, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_MAGE, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_UNDEAD, @CLASS_MAGE, 11, 4604, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_UNDEAD, @CLASS_WARLOCK, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_WARLOCK, 1, 686, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_WARLOCK, 2, 687, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_WARLOCK, 3, 20577, @ACTION_TYPE_SPELL),
    (@RACE_UNDEAD, @CLASS_WARLOCK, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_UNDEAD, @CLASS_WARLOCK, 11, 4604, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_TAUREN, @CLASS_WARRIOR, 72, 6603, @ACTION_TYPE_SPELL),
    (@RACE_TAUREN, @CLASS_WARRIOR, 73, 78, @ACTION_TYPE_SPELL),
    (@RACE_TAUREN, @CLASS_WARRIOR, 74, 20549, @ACTION_TYPE_SPELL),
    (@RACE_TAUREN, @CLASS_WARRIOR, 83, 4540, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_TAUREN, @CLASS_HUNTER, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_TAUREN, @CLASS_HUNTER, 1, 2973, @ACTION_TYPE_SPELL),
    (@RACE_TAUREN, @CLASS_HUNTER, 2, 75, @ACTION_TYPE_SPELL),
    (@RACE_TAUREN, @CLASS_HUNTER, 3, 20549, @ACTION_TYPE_SPELL),
    (@RACE_TAUREN, @CLASS_HUNTER, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_TAUREN, @CLASS_HUNTER, 11, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_TAUREN, @CLASS_SHAMAN, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_TAUREN, @CLASS_SHAMAN, 1, 403, @ACTION_TYPE_SPELL),
    (@RACE_TAUREN, @CLASS_SHAMAN, 2, 331, @ACTION_TYPE_SPELL),
    (@RACE_TAUREN, @CLASS_SHAMAN, 3, 20549, @ACTION_TYPE_SPELL),
    (@RACE_TAUREN, @CLASS_SHAMAN, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_TAUREN, @CLASS_SHAMAN, 11, 4604, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_TAUREN, @CLASS_DRUID, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_TAUREN, @CLASS_DRUID, 1, 5176, @ACTION_TYPE_SPELL),
    (@RACE_TAUREN, @CLASS_DRUID, 2, 5185, @ACTION_TYPE_SPELL),
    (@RACE_TAUREN, @CLASS_DRUID, 3, 20549, @ACTION_TYPE_SPELL),
    (@RACE_TAUREN, @CLASS_DRUID, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_TAUREN, @CLASS_DRUID, 11, 4536, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_GNOME, @CLASS_WARRIOR, 72, 6603, @ACTION_TYPE_SPELL),
    (@RACE_GNOME, @CLASS_WARRIOR, 73, 78, @ACTION_TYPE_SPELL),
    (@RACE_GNOME, @CLASS_WARRIOR, 83, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_GNOME, @CLASS_ROGUE, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_GNOME, @CLASS_ROGUE, 1, 1752, @ACTION_TYPE_SPELL),
    (@RACE_GNOME, @CLASS_ROGUE, 2, 2098, @ACTION_TYPE_SPELL),
    (@RACE_GNOME, @CLASS_ROGUE, 3, 2764, @ACTION_TYPE_SPELL),
    (@RACE_GNOME, @CLASS_ROGUE, 11, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_GNOME, @CLASS_MAGE, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_GNOME, @CLASS_MAGE, 1, 133, @ACTION_TYPE_SPELL),
    (@RACE_GNOME, @CLASS_MAGE, 2, 168, @ACTION_TYPE_SPELL),
    (@RACE_GNOME, @CLASS_MAGE, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_GNOME, @CLASS_MAGE, 11, 4536, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_GNOME, @CLASS_WARLOCK, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_GNOME, @CLASS_WARLOCK, 1, 686, @ACTION_TYPE_SPELL),
    (@RACE_GNOME, @CLASS_WARLOCK, 2, 687, @ACTION_TYPE_SPELL),
    (@RACE_GNOME, @CLASS_WARLOCK, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_GNOME, @CLASS_WARLOCK, 11, 4604, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_TROLL, @CLASS_WARRIOR, 72, 6603, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_WARRIOR, 73, 78, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_WARRIOR, 74, 2764, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_WARRIOR, 75, 26296, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_WARRIOR, 83, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_TROLL, @CLASS_HUNTER, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_HUNTER, 1, 2973, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_HUNTER, 2, 75, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_HUNTER, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_TROLL, @CLASS_HUNTER, 11, 4604, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_TROLL, @CLASS_ROGUE, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_ROGUE, 1, 1752, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_ROGUE, 2, 2098, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_ROGUE, 3, 2764, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_ROGUE, 4, 26972, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_ROGUE, 11, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_TROLL, @CLASS_PRIEST, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_PRIEST, 1, 585, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_PRIEST, 2, 2050, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_PRIEST, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_TROLL, @CLASS_PRIEST, 11, 4540, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_TROLL, @CLASS_SHAMAN, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_SHAMAN, 1, 403, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_SHAMAN, 2, 331, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_SHAMAN, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_TROLL, @CLASS_SHAMAN, 11, 117, @ACTION_TYPE_ITEM);

INSERT INTO `playercreateinfo_action` VALUES
    (@RACE_TROLL, @CLASS_MAGE, 0, 6603, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_MAGE, 1, 133, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_MAGE, 2, 168, @ACTION_TYPE_SPELL),
    (@RACE_TROLL, @CLASS_MAGE, 10, 159, @ACTION_TYPE_ITEM),
    (@RACE_TROLL, @CLASS_MAGE, 11, 117, @ACTION_TYPE_ITEM);
