-- Host: localhost    Database: world
-- ---------------------------------------------------------------------------
-- Add initial data to world database
--
-- We will add strings used by the world server.
--

-- Insert internal world server string into `mangos_string` table ------------
INSERT INTO `mangos_string`
    (`entry`, `content_default`)
VALUES
     (1,    'You should select a character or a creature.')
    ,(2,    'You should select a creature.')
    ,(3,    '|cffff0000[System Message]: %s|r')
    ,(4,    '|cffff0000[Event Message]: %s|r')
    ,(5,    'There is no help for that command')
    ,(6,    'There is no such command')
    ,(7,    'There is no such subcommand')
    ,(8,    'Command %s have subcommands:')
    ,(9,    'Commands available to you:')
    ,(10,   'Incorrect syntax.')
    ,(11,   'Your account level is: %i')
    ,(12,   'Online players: %u (max: %u) Queued players: %u (max: %u)')
    ,(13,   'Server uptime: %s')
    ,(14,   'Player saved.')
    ,(15,   'All players saved.')
    ,(16,   'There are the following active GMs on this server:')
    ,(17,   'There are no GMs currently logged in on this server.')
    ,(18,   'Cannot do that while flying.')
    ,(19,   'Cannot do that in Battlegrounds.')
    ,(20,   'Target is flying you can\'t do that.')
    ,(21,   '%s is flying command failed.')
    ,(22,   'You are not mounted so you can\'t dismount.')
    ,(23,   'Cannot do that while fighting.')
    ,(24,   'You used it recently.')
    ,(25,   'Password not changed (unknown error)!')
    ,(26,   'The password was changed')
    ,(27,   'The old password is wrong')
    ,(28,   'Your account is now locked.')
    ,(29,   'Your account is now unlocked.')
    ,(30,   ', rank ')
    ,(31,   ' [known]')
    ,(32,   ' [learn]')
    ,(33,   ' [passive]')
    ,(34,   ' [talent]')
    ,(35,   ' [active]')
    ,(36,   ' [complete]')
    ,(37,   ' (offline)')
    ,(38,   'on')
    ,(39,   'off')
    ,(40,   'You are: %s')
    ,(41,   'visible')
    ,(42,   'invisible')
    ,(43,   'done')
    ,(44,   'You')
    ,(45,   ' <unknown> ')
    ,(46,   '<error>')
    ,(47,   '<non-existing character>')
    ,(48,   'UNKNOWN')
    ,(49,   'You must be at least level %u to enter.')
    ,(50,   'You must be at least level %u and have item %s to enter.')
    ,(51,   'Hello! Ready for some training?')
    ,(52,   'Invaid item count (%u) for item %u')
    ,(53,   'Mail can\'t have more %u item stacks')
    ,(54,   'The new passwords do not match')
    ,(55,   'Your password can\'t be longer than 16 characters (client limit), password not changed!')
    ,(56,   'Current Message of the day: %s')
    ,(57,   'Using World DB: %s')
    ,(58,   'Using script library: %s')
    ,(59,   'Using creature EventAI: %s')
    ,(61,   'Username: ')
    ,(62,   'Password: ')
    ,(63,   'Accepts whispers')
    ,(64,   'Doesn\'t accept whispers')
    ,(65,   'Using script library: <Unknown Script Library>')
    ,(66,   'Using script library: <No Script Library Loaded>')
    ,(100,  'Global notify: ')
    ,(101,  'Map: %u (%s) Zone: %u (%s) Area: %u (%s)X: %f Y: %f Z: %f Orientation: %fgrid[%u,%u]cell[%u,%u] InstanceID: %u ZoneX: %f ZoneY: %fGroundZ: %f FloorZ: %f Have height data (Map: %u VMap: %u)')
    ,(102,  '%s is already being teleported.')
    ,(103,  'You can summon a player to your instance only if he is in your party with you as leader.')
    ,(104,  'You cannot go to the player\'s instance because you are in a party now.')
    ,(105,  'You can go to the player\'s instance while not being in his party only if your GM mode is on.')
    ,(106,  'You can not go to player %s from instance to instance.')
    ,(107,  'You can not summon player %s from instance to instance.')
    ,(108,  'You are summoning %s%s.')
    ,(109,  'You are being summoned by %s.')
    ,(110,  'You are teleporting %s%s to %s.')
    ,(111,  'You are being teleported by %s.')
    ,(112,  'Player (%s) does not exist.')
    ,(113,  'Appearing at %s\'s location.')
    ,(114,  '%s is appearing to your location.')
    ,(115,  'Incorrect values.')
    ,(116,  'No character selected.')
    ,(117,  '%s is not in a group.')
    ,(118,  'You changed HP of %s to %i/%i.')
    ,(119,  '%s changed your HP to %i/%i.')
    ,(120,  'You changed MANA of %s to %i/%i.')
    ,(121,  '%s changed your MANA to %i/%i.')
    ,(122,  'You changed ENERGY of %s to %i/%i.')
    ,(123,  '%s changed your ENERGY to %i/%i.')
    ,(124,  'Current energy: %u')
    ,(125,  'You changed rage of %s to %i/%i.')
    ,(126,  '%s changed your rage to %i/%i.')
    ,(127,  'You changed level of %s to %i.')
    ,(128,  'GUID %i, faction is %i, flags is %i, npcflag is %i, DY flag is %i')
    ,(129,  'Wrong faction: %u (not found in factiontemplate.dbc).')
    ,(130,  'You changed GUID=%i \'s Faction to %i, flags to %i, npcflag to %i, dyflag to %i.')
    ,(131,  'You changed the %s spellmod %u to value %i for spell with family bit %u for %s.')
    ,(132,  '%s changed your spellmod %u to value %i for spell with family bit %u.')
    ,(133,  '%s has access to all taxi nodes now (until logout).')
    ,(134,  '%s has no more access to all taxi nodes now (only visited accessible).')
    ,(135,  '%s has given you access to all taxi nodes (until logout).')
    ,(136,  '%s has removed access to all taxi nodes (only visited still accessible).')
    ,(137,  'You set all speeds to %2.2f from normal of %s.')
    ,(138,  '%s set all your speeds to %2.2f from normal.')
    ,(139,  'You set the speed to %2.2f from normal of %s.')
    ,(140,  '%s set your speed to %2.2f from normal.')
    ,(141,  'You set the swim speed to %2.2f from normal of %s.')
    ,(142,  '%s set your swim speed to %2.2f from normal.')
    ,(143,  'You set the backwards run speed to %2.2f from normal of %s.')
    ,(144,  '%s set your backwards run speed to %2.2f from normal.')
    ,(147,  'You set the size %2.2f of %s.')
    ,(148,  '%s set your size to %2.2f.')
    ,(149,  'There is no such mount.')
    ,(150,  'You give a mount to %s.')
    ,(151,  '%s gave you a mount.')
    ,(152,  'USER1: %i, ADD: %i, DIF: %i')
    ,(153,  'You take all copper of %s.')
    ,(154,  '%s took you all of your copper.')
    ,(155,  'You take %i copper from %s.')
    ,(156,  '%s took %i copper from you.')
    ,(157,  'You give %i copper to %s.')
    ,(158,  '%s gave you %i copper.')
    ,(159,  'You hear sound %u.')
    ,(160,  'USER2: %i, ADD: %i, RESULT: %i')
    ,(161,  'Removed bit %i in field %i.')
    ,(162,  'Set bit %i in field %i.')
    ,(163,  'Teleport location table is empty!')
    ,(164,  'Teleport location not found!')
    ,(165,  'Requires search parameter.')
    ,(166,  'There are no teleport locations matching your request.')
    ,(168,  'Locations found are: %s')
    ,(169,  'Mail sent to %s')
    ,(170,  'You try to hear sound %u but it doesn\'t exist.')
    ,(171,  'You can\'t teleport self to self!')
    ,(172,  'server console command')
    ,(175,  'Liquid level: %f, ground: %f, type flags %u, status: %d.')
    ,(200,  'No selection.')
    ,(201,  'Object GUID is: %s')
    ,(202,  'The name was too long by %i characters.')
    ,(203,  'Error, name can only contain characters A-Z and a-z.')
    ,(204,  'The subname was too long by %i characters.')
    ,(205,  'Not yet implemented')
    ,(206,  'Item \'%i\' \'%s\' added to list with maxcount \'%i\' and incrtime \'%i\'')
    ,(207,  'Item \'%i\' not found in database.')
    ,(208,  'Item \'%i\' \'%s\' deleted from vendor list')
    ,(209,  'Item \'%i\' not found in vendor list.')
    ,(210,  'Item \'%i\' already in vendor list.')
    ,(211,  'Spells of %s reset.')
    ,(212,  'Spells of %s will reset at next login.')
    ,(213,  'Talents of %s reset.')
    ,(214,  'Talents of %s will reset at next login.')
    ,(215,  'Your spells have been reset.')
    ,(216,  'Your talents have been reset.')
    ,(217,  'Unknown case \'%s\' for .resetall command. Type full correct case name.')
    ,(218,  'Spells will reset for all players at login. Strongly recommend re-login!')
    ,(219,  'Talents will reset for all players at login. Strongly recommend re-login!')
    ,(220,  'Creature (GUID: %u) No waypoint found.')
    ,(221,  'Creature (GUID: %u) Last waypoint not found.')
    ,(222,  'Creature (GUID: %u) No waypoint found - used \'wpguid\'. Now trying to find it by its position...')
    ,(223,  'Creature (GUID: %u) No waypoints found - This is a MaNGOS db problem (single float).')
    ,(224,  'Selected creature is ignored - provided GUID is used')
    ,(225,  'Creature (GUID: %u) not found')
    ,(226,  'You must select a visual waypoint.')
    ,(227,  'No visual waypoints found')
    ,(228,  'Could not create visual waypoint with creatureID: %d')
    ,(229,  'All visual waypoints removed')
    ,(230,  'Could not create waypoint-creature with ID: %d')
    ,(231,  'No GUID provided.')
    ,(232,  'No waypoint number provided.')
    ,(233,  'Argument required for \'%s\'.')
    ,(234,  'Waypoint %i added to GUID: %d')
    ,(235,  'Waypoint %d added.')
    ,(236,  'Waypoint changed.')
    ,(237,  'Waypoint %s modified.')
    ,(238,  'WP export successfull.')
    ,(239,  'No waypoints found inside the database.')
    ,(240,  'File imported.')
    ,(241,  'Waypoint removed.')
    ,(242,  'Warning: Could not delete WP from the world with ID: %d')
    ,(243,  'This happens if the waypoint is too far away from your char.')
    ,(244,  'The WP is deleted from the database, but not from the world here.')
    ,(245,  'They will disappear after a server restart.')
    ,(246,  'Waypoint %d: Info for creature: %s, GUID: %d')
    ,(247,  'Waittime: %d')
    ,(248,  'Model %d: %d')
    ,(249,  'Emote: %d')
    ,(250,  'Spell: %d')
    ,(251,  'Text%d (ID: %i): %s')
    ,(252,  'AIScript: %s')
    ,(253,  'Forced rename for player %s will be requested at next login.')
    ,(254,  'Forced rename for player %s (GUID #%u) will be requested at next login.')
    ,(255,  'Waypoint-Creature (GUID: %u) Not found')
    ,(256,  'Could not find NPC...')
    ,(257,  'Creature movement type set to \'%s\', waypoints removed (if any).')
    ,(258,  'Creature movement type set to \'%s\', waypoints were not removed.')
    ,(259,  'Incorrect value, use on or off')
    ,(260,  'Value saved.')
    ,(261,  'Value saved, you may need to rejoin or clean your client cache.')
    ,(262,  'Areatrigger ID %u not found!')
    ,(263,  'Target map or coordinates is invalid (X: %f Y: %f MapId: %u)')
    ,(264,  'Zone coordinates is invalid (X: %f Y: %f AreaId: %u)')
    ,(265,  'Zone %u (%s) is part of instanceable map %u (%s)')
    ,(266,  'Nothing found!')
    ,(267,  'Object not found!')
    ,(268,  'Creature not found!')
    ,(270,  'Creature Removed')
    ,(271,  'Creature moved.')
    ,(272,  'Creature (GUID:%u) must be on the same map as player!')
    ,(273,  'Game Object (GUID: %u) not found')
    ,(274,  'Game Object (GUID: %u) has references in not found owner %s GO list, can\'t be deleted.')
    ,(275,  'Game Object (GUID: %u) removed')
    ,(276,  'Game Object |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) turned')
    ,(277,  'Game Object |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) moved')
    ,(278,  'You must select a vendor')
    ,(279,  'You must send id for item')
    ,(280,  'Vendor has too many items (max 128)')
    ,(281,  'You can\'t kick self, logout instead')
    ,(282,  'Player %s kicked.')
    ,(284,  'Accepting Whisper: %s')
    ,(285,  'Accepting Whisper: ON')
    ,(286,  'Accepting Whisper: OFF')
    ,(287,  'Creature (GUID: %u) not found')
    ,(288,  'Tickets count: %i show new tickets: %s')
    ,(289,  'New ticket from %s')
    ,(290,  'Ticket of %s (Last updated: %s):%s ')
    ,(291,  'New ticket show: ON')
    ,(292,  'New ticket show: OFF')
    ,(293,  'Ticket %i doesn\'t exist')
    ,(294,  'All tickets deleted.')
    ,(295,  'Character %s ticket deleted.')
    ,(296,  'Ticket deleted.')
    ,(297,  'Spawn distance changed to: %f')
    ,(298,  'Spawn time changed to: %i')
    ,(299,  'The %s field of %s was set to %u')
    ,(300,  'Your chat has been disabled for %u minutes.')
    ,(301,  'You have disabled %s\'s chat for %u minutes.')
    ,(302,  'Player\'s chat is already enabled.')
    ,(303,  'Your chat has been enabled.')
    ,(304,  'You have enabled %s\'s chat.')
    ,(305,  'Faction %s (%u) reputation of %s was set to %5d!')
    ,(307,  'No faction found!')
    ,(308,  'Faction %i unknown!')
    ,(309,  'Invalid parameter %s')
    ,(310,  'delta must be between 0 and %d (inclusive)')
    ,(311,  '%d - |cffffffff|Hfaction:%d|h[%s]|h|r')
    ,(312,  ' [visible]')
    ,(313,  ' [at war]')
    ,(314,  ' [peace forced]')
    ,(315,  ' [hidden]')
    ,(316,  ' [invisible forced]')
    ,(317,  ' [inactive]')
    ,(318,  'Hated')
    ,(319,  'Hostile')
    ,(320,  'Unfriendly')
    ,(321,  'Neutral')
    ,(322,  'Friendly')
    ,(323,  'Honored')
    ,(324,  'Revered')
    ,(325,  'Exalted')
    ,(326,  'Faction %s (%u) can\'not have reputation.')
    ,(327,  ' [no reputation]')
    ,(328,  'Characters at account %s (Id: %u)')
    ,(329,  '  %s (GUID %u)')
    ,(330,  'No players found!')
    ,(331,  'Extended item cost %u not exist')
    ,(332,  'GM mode is ON')
    ,(333,  'GM mode is OFF')
    ,(334,  'GM Chat Badge is ON')
    ,(335,  'GM Chat Badge is OFF')
    ,(336,  'You repair all %s\'s items.')
    ,(337,  'All your items repaired by %s.')
    ,(338,  'You set waterwalk mode %s for %s.')
    ,(339,  'Your waterwalk mode %s by %s.')
    ,(340,  '%s is now following you.')
    ,(341,  '%s is not following you.')
    ,(342,  '%s is now not following you.')
    ,(343,  'Creature (Entry: %u) cannot be tamed.')
    ,(344,  'You already have pet.')
    ,(347,  'TaxiNode ID %u not found!')
    ,(348,  'Game Object (Entry: %u) have invalid data and can\'t be spawned')
    ,(357,  'Areatrigger %u not has target coordinates')
    ,(358,  'No areatriggers found!')
    ,(359,  '%s|cffffffff|Hareatrigger_target:%u|h[Trigger target %u]|h|r Map %u X:%f Y:%f Z:%f%s')
    ,(360,  '%s[Trigger target %u] Map %u X:%f Y:%f Z:%f')
    ,(361,  '|cffffffff|Hareatrigger:%u|h[Trigger %u]|h|r Map %u X:%f Y:%f Z:%f%s%s%s')
    ,(362,  '[Trigger %u] Map %u X:%f Y:%f Z:%f%s%s')
    ,(363,  ' (Dist %f)')
    ,(364,  ' [Tavern]')
    ,(365,  ' [Quest]')
    ,(366,  'Explore quest:')
    ,(367,  'Required level %u')
    ,(368,  'Required Items:')
    ,(369,  'Required quest:')
    ,(373,  'Response:\n%s ')
    ,(374,  'Tickets count: %i\n')
    ,(375,  'Player %s not have tickets.')
    ,(376,  '%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u')
    ,(377,  'No pools found for map \'%s\' (Id:%u)')
    ,(378,  'You can\'t use this command at non-instanceable map \'%s\' (Id:%u). Use .lookup pool command instead.')
    ,(379,  'You can\'t use this command without args at non-instanceable map \'%s\' (Id:%u).')
    ,(380,  '%d%s - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r Chance:%f %s')
    ,(381,  '%d%s - [%s] X:%f Y:%f Z:%f MapId:%d Chance:%f %s')
    ,(382,  '%d%s - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r %s')
    ,(383,  '%d%s - [%s] X:%f Y:%f Z:%f MapId:%d %s')
    ,(384,  '%d%s - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r Chance:%f %s')
    ,(385,  '%d%s - [%s] X:%f Y:%f Z:%f MapId:%d Chance:%f %s')
    ,(386,  '%d%s - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r %s')
    ,(387,  '%d%s - [%s] X:%f Y:%f Z:%f MapId:%d %s')
    ,(388,  'Creatures with explicitly chance:')
    ,(389,  'Creatures with equal chance:')
    ,(390,  'Gameobjects with explicitly chance:')
    ,(391,  'Gameobjects with equal chance:')
    ,(392,  'Pool %u - Mother pool: %u |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u')
    ,(393,  'Pool %u - Mother pool: %u [%s] AutoSpawn: %u MaxLimit: %u')
    ,(394,  'Pool %u - Mother pool: none AutoSpawn: %u MaxLimit: %u')
    ,(395,  'No pools found')
    ,(396,  '%u - [%s] AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u')
    ,(397,  'Pools with explicitly chance:')
    ,(398,  'Pools with equal chance:')
    ,(399,  '%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u Chance: %f %s')
    ,(400,  '|cffff0000[System Message]:|rScripts reloaded')
    ,(401,  'You change security level of account %s to %i.')
    ,(402,  '%s changed your security level to %i.')
    ,(403,  'You have low security level for this.')
    ,(404,  'Creature movement disabled.')
    ,(405,  'Creature movement enabled.')
    ,(406,  'Weather can\'t be changed for this zone.')
    ,(407,  'Weather system disabled at server.')
    ,(408,  '%s is banned for %s. Reason: %s.')
    ,(409,  '%s is banned permanently for %s.')
    ,(410,  '%s %s not found')
    ,(411,  '%s unbanned.')
    ,(412,  'There was an error removing the ban on %s.')
    ,(413,  'Account not exist: %s')
    ,(414,  'There is no such character.')
    ,(415,  'There is no such IP in banlist.')
    ,(416,  'Account %s has never been banned')
    ,(417,  'Ban history for account %s:')
    ,(418,  'Ban Date: %s Bantime: %s Still active: %s  Reason: %s Set by: %s')
    ,(419,  'Inf.')
    ,(420,  'Never')
    ,(421,  'Yes')
    ,(422,  'No')
    ,(423,  'IP: %sBan Date: %sUnban Date: %sRemaining: %sReason: %sSet by: %s')
    ,(424,  'There is no matching IPban.')
    ,(425,  'There is no matching account.')
    ,(426,  'There is no banned account owning a character matching this part.')
    ,(427,  'The following IPs match your pattern:')
    ,(428,  'The following accounts match your query:')
    ,(429,  'You learned many spells/skills.')
    ,(430,  'You learned all spells for class.')
    ,(431,  'You learned all talents for class.')
    ,(432,  'You learned all languages.')
    ,(433,  'You learned all craft skills and recipes.')
    ,(434,  'Could not find \'%s\'')
    ,(435,  'Invalid item id: %u')
    ,(436,  'No items found!')
    ,(437,  'Invalid gameobject id: %u')
    ,(438,  'Found items %u: %u ( inventory %u mail %u auction %u guild %u)')
    ,(439,  'Found gameobjects %u: %u ')
    ,(440,  'Invalid creature id: %u')
    ,(441,  'Found creatures %u: %u ')
    ,(442,  'No area found!')
    ,(443,  'No item sets found!')
    ,(444,  'No skills found!')
    ,(445,  'No spells found!')
    ,(446,  'No quests found!')
    ,(447,  'No creatures found!')
    ,(448,  'No gameobjects found!')
    ,(449,  'Graveyard #%u doesn\'t exist.')
    ,(450,  'Graveyard #%u already linked to zone #%u (current).')
    ,(451,  'Graveyard #%u linked to zone #%u (current).')
    ,(452,  'Graveyard #%u can\'t be linked to subzone or not existed zone #%u (internal error).')
    ,(454,  'No faction in Graveyard with id= #%u , fix your DB')
    ,(455,  'invalid team, please fix database')
    ,(456,  'any')
    ,(457,  'alliance')
    ,(458,  'horde')
    ,(459,  'Graveyard #%u (faction: %s) is nearest from linked to zone #%u.')
    ,(460,  'Zone #%u doesn\'t have linked graveyards.')
    ,(461,  'Zone #%u doesn\'t have linked graveyards for faction: %s.')
    ,(462,  'Teleport location already exists!')
    ,(463,  'Teleport location added.')
    ,(464,  'Teleport location NOT added: database error.')
    ,(465,  'Teleport location deleted.')
    ,(466,  'No taxinodes found!')
    ,(467,  'Target unit has %d auras:')
    ,(468,  'id: %d eff: %d type: %d duration: %d maxduration: %d name: %s%s%s caster: %s')
    ,(469,  'Target unit has %d auras of type %d:')
    ,(470,  'id: %d eff: %d name: %s%s%s caster: %s')
    ,(471,  'Quest %u not found.')
    ,(472,  'Quest %u started from item. For correct work, please, add item to inventory and start quest in normal way: .additem %u')
    ,(473,  'Quest removed.')
    ,(474,  ' [rewarded]')
    ,(475,  ' [complete]')
    ,(476,  ' [active]')
    ,(477,  '%s\'s Fly Mode %s')
    ,(478,  'Opcode %u sent to %s')
    ,(479,  'Character loaded successfully!')
    ,(480,  'Failed to load the character!')
    ,(481,  'Character dumped successfully!')
    ,(482,  'Character dump failed!')
    ,(483,  'Spell %u broken and not allowed to cast or learn!')
    ,(484,  'Skill %u (%s) for player %s set to %u and current maximum set to %u (without permanent (talent) bonuses).')
    ,(485,  'Player %s must have skill %u (%s) before using this command.')
    ,(486,  'Invalid skill id (%u)')
    ,(487,  'You learned default GM spells/skills.')
    ,(488,  'You already know that spell.')
    ,(489,  'Target(%s) already know that spell.')
    ,(490,  '%s doesn\'t know that spell.')
    ,(491,  'You already forgot that spell.')
    ,(492,  'All spell cooldowns removed for %s.')
    ,(493,  'Spell %u cooldown removed for %s.')
    ,(494,  'Command : Additem, itemId = %i, amount = %i')
    ,(495,  'Command : Additemset, itemsetId = %i')
    ,(496,  'Removed itemID = %i, amount = %i from %s')
    ,(497,  'Cannot create item \'%i\' (amount: %i)')
    ,(498,  'You need to provide a guild name!')
    ,(499,  'Player not found!')
    ,(500,  'Player already has a guild!')
    ,(501,  'Guild not created! (already exists?)')
    ,(502,  'No items from itemset \'%u\' found.')
    ,(503,  'The distance is: (3D) %f (2D) %f - (3D, point-to-point) %f yards.')
    ,(504,  'Item \'%i\' \'%s\' Item Slot %i')
    ,(505,  'Item \'%i\' doesn\'t exist.')
    ,(506,  'Item \'%i\' \'%s\' Added to Slot %i')
    ,(507,  'Item save failed!')
    ,(508,  '%d - owner: %s (guid: %u account: %u ) %s')
    ,(509,  '%d - sender: %s (guid: %u account: %u ) receiver: %s (guid: %u account: %u ) %s')
    ,(510,  '%d - owner: %s (guid: %u account: %u ) %s')
    ,(511,  'Wrong link type!')
    ,(512,  '%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0|h[%s]|h|r %s')
    ,(513,  '%d - |cffffffff|Hquest:%d:%d|h[%s]|h|r %s')
    ,(514,  '%d - |cffffffff|Hcreature_entry:%d|h[%s]|h|r ')
    ,(515,  '%d%s - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ')
    ,(516,  '%d - |cffffffff|Hgameobject_entry:%d|h[%s]|h|r ')
    ,(517,  '%d%s, Entry %d - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r')
    ,(518,  '%d - |cffffffff|Hitemset:%d|h[%s %s]|h|r ')
    ,(519,  '|cffffffff|Htele:%s|h[%s]|h|r ')
    ,(520,  '%d - |cffffffff|Hspell:%d|h[%s]|h|r ')
    ,(521,  '%d - |cffffffff|Hskill:%d|h[%s %s]|h|r %s %s')
    ,(522,  'Game Object (Entry: %u) not found')
    ,(523,  '>> Game Object %s (GUID: %u) at %f %f %f. Orientation %f.')
    ,(524,  'Selected object:|cffffffff|Hgameobject:%d|h[%s]|h|r GUID: %u ID: %uX: %f Y: %f Z: %f MapId: %uOrientation: %f')
    ,(525,  '>> Add Game Object \'%i\' (%s) (GUID: %i) added at \'%f %f %f\'.')
    ,(526,  '%s (lowguid: %u) movement generators stack:')
    ,(527,  '   Idle')
    ,(528,  '   Random')
    ,(529,  '   Waypoint')
    ,(530,  '   Animal random')
    ,(531,  '   Confused')
    ,(532,  '   Targeted to player %s (lowguid %u)')
    ,(533,  '   Targeted to creature %s (lowguid %u)')
    ,(534,  '   Targeted to <NULL>')
    ,(535,  '   Home movement to (X:%f Y:%f Z:%f)')
    ,(536,  '   Home movement used for player?!?')
    ,(537,  '   Taxi flight')
    ,(538,  '   Unknown movement generator (%u)')
    ,(539,  'Player selected: %s.\nFaction: %u.\nnpcFlags: %u.\nEntry: %u.\nDisplayID: %u (Native: %u).')
    ,(540,  'Level: %u.')
    ,(541,  'Health (base): %u. (max): %u. (current): %u.')
    ,(542,  'Unit Flags: %u.\nDynamic Flags: %u.\nFaction Template: %u.')
    ,(543,  'Loot: %u Pickpocket: %u Skinning: %u')
    ,(544,  'Position: %f %f %f.')
    ,(545,  '*** Is a vendor!')
    ,(546,  '*** Is a trainer!')
    ,(547,  'InstanceID: %u')
    ,(548,  'Player%s %s (guid: %u) Account: %s (id: %u) GMLevel: %u E-mail: %s Last IP: %s Last login: %s Latency: %ums')
    ,(549,  'Played time: %s Level: %u Money: %ug%us%uc')
    ,(550,  'Command .pinfo doesn\'t support \'rep\' option for offline players.')
    ,(551,  '%s has explored all zones now.')
    ,(552,  '%s has no more explored zones.')
    ,(553,  '%s has explored all zones for you.')
    ,(554,  '%s has hidden all zones from you.')
    ,(557,  '%s level up you to (%i)')
    ,(558,  '%s level down you to (%i)')
    ,(559,  '%s reset your level progress.')
    ,(560,  'The area has been set as explored.')
    ,(561,  'The area has been set as not explored.')
    ,(564,  'The value index %u is too big to %s (count: %u).')
    ,(565,  'Set for %s field:%u to uint32 value:%u')
    ,(566,  'You set for %s field:%u to uint32 value: %u')
    ,(567,  'Set for %s field:%u to to float value:%f')
    ,(568,  'You set for %s field:%u to float value: %f')
    ,(569,  'Get %s uint32 value:[FIELD]:%u [VALUE]:%u')
    ,(570,  '%s has uint32 value:[FIELD]:%u [VALUE]:%u')
    ,(571,  'Get %s float value:[FIELD]:%u [VALUE]:%f')
    ,(572,  '%s has float value:[FIELD]:%u [VALUE]:%f')
    ,(575,  'Modify %s uint32 field:%u to sum with:%i = %u (%i)')
    ,(576,  'You modify for %s uint32 field:%u to sum with:%i = %u (%i)')
    ,(577,  'You are now invisible.')
    ,(578,  'You are now visible.')
    ,(579,  'Selected player or creature not have victim.')
    ,(580,  'You learned all default spells for race/class and completed quests rewarded spells.')
    ,(581,  'Found near gameobjects (distance %f): %u ')
    ,(582,  'SpawnTime: Full:%s Remain:%s')
    ,(583,  '%d - |cffffffff|Hgameevent:%d|h[%s]|h|r%s')
    ,(584,  'No event found!')
    ,(585,  'Event not exist!')
    ,(586,  'Event %u: %s%sStart: %s End: %s Occurence: %s Length: %sNext state change: %s')
    ,(587,  'Event %u already active!')
    ,(588,  'Event %u not active!')
    ,(589,  '   Point movement to (X:%f Y:%f Z:%f)')
    ,(590,  '   Fear movement')
    ,(591,  '   Distract movement')
    ,(592,  'You have learned all spells in craft: %s')
    ,(593,  'Currently Banned Accounts:')
    ,(594,  '|    Account    |   BanDate    |   UnbanDate  |  Banned By    |   Ban Reason  |')
    ,(595,  'Currently Banned IPs:')
    ,(596,  '|      IP       |   BanDate    |   UnbanDate  |  Banned By    |   Ban Reason  |')
    ,(597,  'Current gamemasters:')
    ,(598,  '|    Account    |  GM  |')
    ,(599,  'No gamemasters.')
    ,(600,  'The Alliance wins!')
    ,(601,  'The Horde wins!')
    ,(602,  'The battle for Warsong Gulch begins in 1 minute.')
    ,(603,  'The battle for Warsong Gulch begins in 30 seconds. Prepare yourselves!')
    ,(604,  'Let the battle for Warsong Gulch begin!')
    ,(605,  '$n captured the Horde flag!')
    ,(606,  '$n captured the Alliance flag!')
    ,(607,  'The Horde flag was dropped by $n!')
    ,(608,  'The Alliance Flag was dropped by $n!')
    ,(609,  'The Alliance Flag was returned to its base by $n!')
    ,(610,  'The Horde flag was returned to its base by $n!')
    ,(611,  'The Horde flag was picked up by $n!')
    ,(612,  'The Alliance Flag was picked up by $n!')
    ,(613,  'The flags are now placed at their bases.')
    ,(614,  'The Alliance flag is now placed at its base.')
    ,(615,  'The Horde flag is now placed at its base.')
    ,(650,  'Alliance')
    ,(651,  'Horde')
    ,(652,  'stables')
    ,(653,  'blacksmith')
    ,(654,  'farm')
    ,(655,  'lumber mill')
    ,(656,  'mine')
    ,(657,  'The %s has taken the %s')
    ,(658,  '$n has defended the %s')
    ,(659,  '$n has assaulted the %s')
    ,(660,  '$n claims the %s! If left unchallenged, the %s will control it in 1 minute!')
    ,(661,  'The Battle for Arathi Basin begins in 1 minute.')
    ,(662,  'The Battle for Arathi Basin begins in 30 seconds. Prepare yourselves!')
    ,(663,  'The Battle for Arathi Basin has begun!')
    ,(664,  'The Alliance has gathered $1776W resources, and is near victory!')
    ,(665,  'The Horde has gathered $1777W resources, and is near victory!')
    ,(666,  'After your recent battle in %s our best attempts to award you a Mark of Honor failed. Enclosed you will find the Mark of Honor we were not able to deliver to you at the time. Thanks for fighting in %s!')
    ,(705,  'You must wait %s before speaking again.')
    ,(706,  'This item(s) has problems with equipping/storing to inventory.')
    ,(707,  '%s does not wish to be disturbed: %s')
    ,(708,  '%s is Away from Keyboard: %s')
    ,(709,  'Do not Disturb')
    ,(710,  'Away from Keyboard')
    ,(711,  'Queue status for %s (Lvl: %u to %u)Queued alliances: %u (Need at least %u more)Queued hordes: %u (Need at least %u more)')
    ,(712,  '|cffff0000[BG Queue Announcer]:|r %s -- [%u-%u] A: %u/%u, H: %u/%u|r')
    ,(715,  'You don\'t meet Battleground level requirements')
    ,(717,  '|cffff0000[BG Queue Announcer]:|r %s -- [%u-%u] Started!|r')
    ,(720,  'Your group is too large for this battleground. Please regroup to join.')
    ,(727,  'Your group has an offline member. Please remove him before joining.')
    ,(728,  'Your group has players from the opposing faction. You can\'t join the battleground as a group.')
    ,(729,  'Your group has players from different battleground brakets. You can\'t join as group.')
    ,(730,  'Someone in your party is already in this battleground queue. (S)he must leave it before joining as group.')
    ,(731,  'Someone in your party is Deserter. You can\'t join as group.')
    ,(732,  'Someone in your party is already in three battleground queues. You cannot join as group.')
    ,(733,  'You cannot teleport to a battleground map.')
    ,(734,  'You cannot summon players to a battleground or arena map.')
    ,(735,  'You must be in GM mode to teleport to a player in a battleground.')
    ,(736,  'You cannot teleport to a battleground from another battleground. Please leave the current battleground first.')
    ,(739,  'Battlegrounds are set to 1v0 for debugging.')
    ,(740,  'Battlegrounds are set to normal playercount.')
    ,(750,  'Not enough players. This game will close in %u mins.')
    ,(751,  'Not enough players. This game will close in %u seconds.')
    ,(752,  'Only the Alliance can use that portal')
    ,(753,  'Only the Horde can use that portal')
    ,(759,  '%s was destroyed by the %s!')
    ,(760,  'The %s is under attack! If left unchecked, the %s will destroy it!')
    ,(761,  'The %s was taken by the %s!')
    ,(762,  'The %s was taken by the %s!')
    ,(763,  'The %s was taken by the %s!')
    ,(764,  'The %s is under attack! If left unchecked, the %s will capture it!')
    ,(765,  'The %s has taken the %s! Its supplies will now be used for reinforcements!')
    ,(766,  'Irondeep Mine')
    ,(767,  'Coldtooth Mine')
    ,(768,  'Stormpike Aid Station')
    ,(769,  'Dun Baldar South Bunker')
    ,(770,  'Dun Baldar North Bunker')
    ,(771,  'Stormpike Graveyard')
    ,(772,  'Icewing Bunker')
    ,(773,  'Stonehearth Graveyard')
    ,(774,  'Stonehearth Bunker')
    ,(775,  'Snowfall Graveyard')
    ,(776,  'Iceblood Tower')
    ,(777,  'Iceblood Graveyard')
    ,(778,  'Tower Point')
    ,(779,  'Frostwolf Graveyard')
    ,(780,  'East Frostwolf Tower')
    ,(781,  'West Frostwolf Tower')
    ,(782,  'Frostwolf Relief Hut')
    ,(784,  '1 minute until the battle for Alterac Valley begins.')
    ,(785,  '30 seconds until the battle for Alterac Valley begins. Prepare yourselves!')
    ,(786,  'The battle for Alterac Valley has begun!')
    ,(787,  'The Alliance Team is running out of reinforcements!')
    ,(788,  'The Horde Team is running out of reinforcements!')
    ,(789,  'The Frostwolf General is Dead!')
    ,(790,  'The Stormpike General is Dead!')
    ,(801,  'You do not have enough gold')
    ,(802,  'You do not have enough free slots')
    ,(803,  'Your partner does not have enough free bag slots')
    ,(804,  'You do not have permission to perform that function')
    ,(805,  'Unknown language')
    ,(806,  'You don\'t know that language')
    ,(807,  'Please provide character name')
    ,(808,  'Player %s not found or offline')
    ,(809,  'Account for character %s not found')
    ,(811,  'Guild Master')
    ,(812,  'Officer')
    ,(813,  'Veteran')
    ,(814,  'Member')
    ,(815,  'Initiate')
    ,(1000, 'Exiting daemon...')
    ,(1001, 'Account deleted: %s')
    ,(1002, 'Account %s NOT deleted (probably sql file format was updated)')
    ,(1003, 'Account %s NOT deleted (unknown error)')
    ,(1004, 'Account created: %s')
    ,(1005, 'Account name cannot be longer than 16 characters (client limit), account not created!')
    ,(1006, 'Account with this name already exist!')
    ,(1007, 'Account %s NOT created (probably sql file format was updated)')
    ,(1008, 'Account %s NOT created (unknown error)')
    ,(1009, 'Player %s (Guid: %u) Account %s (Id: %u) deleted.')
    ,(1010, '| ID         |    Account    |       Character      |       IP        | GM | Expansion |')
    ,(1012, '========================================================================================')
    ,(1013, '| %10u |%15s| %20s | %15s |%4d| %9d |')
    ,(1014, 'No online players.')
    ,(1015, 'Can only quit from a Remote Admin console or the quit command was not entered in full (quit).')
    ,(1016, '| GUID       | Name                 | Account                      | Delete Date         |')
    ,(1017, '| %10u | %20s | %15s (%10u) | %19s |')
    ,(1018, '==========================================================================================')
    ,(1019, 'No characters found.')
    ,(1020, 'Restoring the following characters:')
    ,(1021, 'Deleting the following characters:')
    ,(1022, 'ERROR: You can only assign a new name for a single selected character!')
    ,(1023, 'Character \'%s\' (GUID: %u Account %u) can\'t be restored: account doesn\'t exist!')
    ,(1024, 'Character \'%s\' (GUID: %u Account %u) can\'t be restored: account character list full!')
    ,(1025, 'Character \'%s\' (GUID: %u Account %u) can\'t be restored: name already in use!')
    ,(1026, 'GUID: %u Name: %s Account: %s (%u) Date: %s')
    ,(1027, 'Log filters state:')
    ,(1028, 'All log filters set to: %s')
    ,(1029, 'Command can only be called from a Remote Admin console.')
    ,(1100, 'Account %s (Id: %u) has been granted %u expansion rights.')
    ,(1101, 'Message of the day changed to:%s')
    ,(1102, 'Message sent to %s: %s')
    ,(1103, '%d - %s %s')
    ,(1104, '%d - %s')
    ,(1105, '%d - %s %s')
    ,(1106, '%d - %s %s')
    ,(1107, '%d - %s')
    ,(1108, '%d - %s %s')
    ,(1109, '%d - %s %s %s %s')
    ,(1110, '%d%s - %s X:%f Y:%f Z:%f MapId:%d')
    ,(1111, '%d%s - %s X:%f Y:%f Z:%f MapId:%d')
    ,(1112, 'Failed to open file: %s')
    ,(1113, 'Account %s (%u) have max amount allowed characters (client limit)')
    ,(1114, 'Dump file have broken data!')
    ,(1115, 'Invalid character name!')
    ,(1116, 'Invalid character guid!')
    ,(1117, 'Character guid %u in use!')
    ,(1118, '%d - guild: %s (guid: %u) %s')
    ,(1119, 'You must use male or female as gender.')
    ,(1120, 'You change gender of %s to %s.')
    ,(1121, 'Your gender changed to %s by %s.')
    ,(1122, '(%u/%u +perm %u +temp %u)')
    ,(1128, '%d - |cffffffff|Htaxinode:%u|h[%s %s]|h|r (Map:%u X:%f Y:%f Z:%f)')
    ,(1129, '%d - %s %s (Map:%u X:%f Y:%f Z:%f)')
    ,(1130, 'event started %u \"%s\"')
    ,(1131, 'event stopped %u \"%s\"')
    ,(1132, '   Follow player %s (lowguid %u)')
    ,(1133, '   Follow creature %s (lowguid %u)')
    ,(1134, '   Follow <NULL>')
    ,(1135, 'List known talents:')
    ,(1136, '   (Found talents: %u used talent points: %u)')
    ,(1137, '%d%s - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ')
    ,(1138, '=================================================================================')
    ,(1139, '| GUID       | Name                 | Race            | Class           | Level |')
    ,(1140, '| %10u | %20s | %15s | %15s | %5u |')
    ,(1141, '%u - |cffffffff|Hplayer:%s|h[%s]|h|r %s %s %u')
    ,(1142, '%u - %s (Online:%s IP:%s GM:%u Expansion:%u)')
    ,(1143, 'Spawned by event %u (%s)')
    ,(1144, 'Despawned by event %u (%s)')
    ,(1145, 'Part of pool %u')
    ,(1146, 'Part of pool %u, top pool %u')
    ,(1147, 'The (top)pool %u is spawned by event %u (%s)')
    ,(1148, 'The (top)pool %u is despawned by event %u (%s)')
    ,(1149, ' (Pool %u)')
    ,(1150, ' (Event %i)')
    ,(1151, ' (Pool %u Event %i)')
    ,(1152, '[usable]')
    ,(1153, 'Get %s bitstr value:[FIELD]:%u [VALUE]:%s')
    ,(1154, '%s has bitstr value:[FIELD]:%u [VALUE]:%s')
    ,(1155, 'Get %s hex value:[FIELD]:%u [VALUE]:%x')
    ,(1156, '%s has hex value:[FIELD]:%u [VALUE]:%x')
    ,(1157, 'Modify %s hex field:%u %s %x = %x (hex)')
    ,(1158, 'You modify for %s hex field:%u %s %x = %x (hex)')
    ,(1159, 'Modify %s float field:%u to sum with:%f = %f')
    ,(1160, 'You modify for %s float field:%u to sum with:%f = %f')
    ,(1165, 'Spell %u not have auras.')
    ,(1166, 'Scripting library not found or not accessible.')
    ,(1167, 'Scripting library has wrong list functions (outdated?).')
    ,(1168, 'Scripting library reloaded.')
    ,(1169, 'Scripting library build for different mangosd revision.')
    ,(1171, 'All config are reloaded from ahbot configuration file.')
    ,(1172, 'Error while trying to reload ahbot config.')
    ,(1173, '==========================================================')
    ,(1174, '|--------------------------------------------------------|')
    ,(1175, '|            | Alliance |  Horde   | Neutral  |  Total   |')
    ,(1176, '          Alliance/Horde/Neutral/Total')
    ,(1177, '| %-10s | %8u | %8u | %8u | %8u |')
    ,(1178, '%-10s = %6u / %6u / %6u / %6u')
    ,(1179, 'Count')
    ,(1180, 'Item Ratio')
    ,(1181, '|            | Alliance |   Horde  | Neutral  |  Amount  |')
    ,(1182, '          Alliance/Horde/Neutral/Amount')
    ,(1183, 'Grey')
    ,(1184, 'White')
    ,(1185, 'Green')
    ,(1186, 'Blue')
    ,(1187, 'Purple')
    ,(1188, 'Orange')
    ,(1189, 'Yellow')
    ,(1190, 'Amount of %s items is set to %u.')
    ,(1191, 'Items ratio for %s is set to %u.')
    ,(1192, 'Effect movement')
    ,(1194, 'Current State Information: GOState %u, LootState %u. Collision %s')
    ,(1195, 'Current State Information: GOState %u, LootState %u. Collision %s, (door %s by default)')
    ,(1200, 'You try to view cinematic %u but it doesn\'t exist.')
    ,(1202, 'Spell %u %s = %f (*1.88 = %f) DB = %f AP = %f')
    ,(1203, 'direct heal')
    ,(1204, 'direct damage')
    ,(1205, 'dot heal')
    ,(1206, 'dot damage')
    ,(1400, 'Private ')
    ,(1401, 'Corporal ')
    ,(1402, 'Sergeant ')
    ,(1403, 'Master Sergeant ')
    ,(1404, 'Sergeant Major ')
    ,(1405, 'Knight ')
    ,(1406, 'Knight-Lieutenant ')
    ,(1407, 'Knight-Captain ')
    ,(1408, 'Knight-Champion ')
    ,(1409, 'Lieutenant Commander ')
    ,(1410, 'Commander ')
    ,(1411, 'Marshal ')
    ,(1412, 'Field Marshal ')
    ,(1413, 'Grand Marshal ')
    ,(1414, 'Scout ')
    ,(1415, 'Grunt ')
    ,(1416, 'Sergeant ')
    ,(1417, 'Senior Sergeant ')
    ,(1418, 'First Sergeant ')
    ,(1419, 'Stone Guard ')
    ,(1420, 'Blood Guard ')
    ,(1421, 'Legionnare ')
    ,(1422, 'Centurion ')
    ,(1423, 'Champion ')
    ,(1424, 'Lieutenant General ')
    ,(1425, 'General ')
    ,(1426, 'Warlord ')
    ,(1427, 'High Warlord ')
    ,(1428, 'Game Master ')
    ,(1429, 'No Rank ')
    ,(1430, 'Dishonored ')
    ,(1431, 'Exiled ')
    ,(1432, 'Outlaw ')
    ,(1433, 'Pariah ')
    ,(1434, 'Player: %s - %s (Rank %u)')
    ,(1435, 'Today: [Honorable Kills: |c0000ff00%u|r] [Dishonorable Kills: |c00ff0000%u|r]')
    ,(1436, 'Yesterday: [Kills: |c0000ff00%u|r] [Honor: %u]')
    ,(1437, 'This Week: [Kills: |c0000ff00%u|r] [Honor: %u]')
    ,(1438, 'Last Week: [Kills: |c0000ff00%u|r] [Honor: %u] [Standing: %u]')
    ,(1439, 'Life Time: [Rank Points: |c0000ff00%f|r] [Honorable Kills: |c0000ff00%u|r] [Dishonorable Kills: |c00ff0000%u|r] [Highest Rank %u: %s]')
    ,(1500, '%u - [%s] AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u Chance: %f %s')
    ,(1501, '%u - |cffffffff|Hpool:%u|h[%s]|h|r AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u %s')
    ,(1502, '%u - [%s] AutoSpawn: %u MaxLimit: %u Creatures: %u GameObjecs: %u Pools %u %s')
    ,(1503, 'Cannot add spawn because no free guids for static spawn in reserved guids range. Server restart is required before command can be used. Also look GuidReserveSize.* config options.')
    ,(1504, 'AI-Information for Npc Entry %u')
    ,(1505, 'AIName: %s (%s) ScriptName: %s')
    ,(1506, 'Current phase = %u')
    ,(1507, 'Combat-Movement is %s')
    ,(1508, 'Melee attacking is %s')
    ,(1509, 'Pool %u not found (Maximal pool entry is %u)')
    ,(1600, '|cffffff00Northpass Tower has been taken by the Horde!|r')
    ,(1601, '|cffffff00Northpass Tower has been taken by the Alliance!|r')
    ,(1602, '|cffffff00Crown Guard Tower has been taken by the Horde!|r')
    ,(1603, '|cffffff00Crown Guard Tower has been taken by the Alliance!|r')
    ,(1604, '|cffffff00Eastwall Tower has been taken by the Horde!|r')
    ,(1605, '|cffffff00Eastwall Tower has been taken by the Alliance!|r')
    ,(1606, '|cffffff00The Plaguewood Tower has been taken by the Horde!|r')
    ,(1607, '|cffffff00The Plaguewood Tower has been taken by the Alliance!|r')
    ,(1635, '|cffffff00The Horde has collected 200 silithyst!|r')
    ,(1636, '|cffffff00The Alliance has collected 200 silithyst!|r')
;
