-- Host: localhost    Database: world
-- ---------------------------------------------------------------------------
-- Add initial data to world database
--
-- We will add player information for spells avalable.
--

-- Provide variables for races, and classes ----------------------------------
SET @RACE_HUMAN                                 = 1;
SET @RACE_ORC                                   = 2;
SET @RACE_DWARF                                 = 3;
SET @RACE_NIGHT_ELF                             = 4;
SET @RACE_UNDEAD                                = 5;
SET @RACE_TAUREN                                = 6;
SET @RACE_GNOME                                 = 7;
SET @RACE_TROLL                                 = 8;

SET @CLASS_WARRIOR                              = 1;
SET @CLASS_PALADIN                              = 2;
SET @CLASS_HUNTER                               = 3;
SET @CLASS_ROGUE                                = 4;
SET @CLASS_PRIEST                               = 5;
SET @CLASS_SHAMAN                               = 7;
SET @CLASS_MAGE                                 = 8;
SET @CLASS_WARLOCK                              = 9;
SET @CLASS_DRUID                                = 11;

-- Insert information for player characters and their spells -----------------
INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_HUMAN, @CLASS_WARRIOR, 78, 'Heroic Strike')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 81, 'Dodge')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 107, 'Block')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 196, 'One-Handed Axes')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 198, 'One-Handed Maces')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 201, 'One-Handed Swords')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 203, 'Unarmed')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 204, 'Defense')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 668, 'Language Common')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 2382, 'Generic')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 2457, 'Battle Stance')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 2479, 'Honorless Target')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 3050, 'Detect')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 3365, 'Opening')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 5301, 'Defensive State (DND)')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 6233, 'Closing')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 6246, 'Closing')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 6247, 'Opening')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 6477, 'Opening')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 6478, 'Opening')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 6603, 'Attack')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 7266, 'Duel')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 7267, 'Grovel')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 7355, 'Stuck')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 8386, 'Attacking')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 8737, 'Mail')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 9077, 'Leather')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 9078, 'Cloth')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 9116, 'Shield')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 9125, 'Generic')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 20597, 'Sword Specialization')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 20598, 'The Human Spirit')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 20599, 'Diplomacy')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 20600, 'Perception')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 20864, 'Mace Specialization')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 21651, 'Opening')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 21652, 'Closing')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 22027, 'Remove Insignia')
    ,(@RACE_HUMAN, @CLASS_WARRIOR, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_HUMAN, @CLASS_PALADIN, 81, 'Dodge')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 107, 'Block')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 198, 'One-Handed Maces')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 199, 'Two-Handed Maces')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 203, 'Unarmed')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 204, 'Defense')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 635, 'Holy Light')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 668, 'Language Common')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 2382, 'Generic')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 2479, 'Honorless Target')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 3050, 'Detect')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 3365, 'Opening')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 6233, 'Closing')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 6246, 'Closing')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 6247, 'Opening')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 6477, 'Opening')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 6478, 'Opening')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 6603, 'Attack')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 7266, 'Duel')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 7267, 'Grovel')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 7355, 'Stuck')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 8386, 'Attacking')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 8737, 'Mail')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 9077, 'Leather')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 9078, 'Cloth')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 9116, 'Shield')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 9125, 'Generic')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 20597, 'Sword Specialization')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 20598, 'The Human Spirit')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 20599, 'Diplomacy')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 20600, 'Perception')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 20864, 'Mace Specialization')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 21084, 'Seal of Righteousness')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 21651, 'Opening')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 21652, 'Closing')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 22027, 'Remove Insignia')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 22810, 'Opening - No Text')
    ,(@RACE_HUMAN, @CLASS_PALADIN, 27762, 'Libram')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_HUMAN, @CLASS_ROGUE, 81, 'Dodge')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 203, 'Unarmed')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 204, 'Defense')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 668, 'Language Common')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 1180, 'Daggers')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 1752, 'Sinister Strike')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 2098, 'Eviscerate')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 2382, 'Generic')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 2479, 'Honorless Target')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 2567, 'Thrown')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 2764, 'Throw')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 3050, 'Detect')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 3365, 'Opening')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 6233, 'Closing')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 6246, 'Closing')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 6247, 'Opening')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 6477, 'Opening')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 6478, 'Opening')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 6603, 'Attack')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 7266, 'Duel')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 7267, 'Grovel')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 7355, 'Stuck')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 8386, 'Attacking')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 9077, 'Leather')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 9078, 'Cloth')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 9125, 'Generic')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 16092, 'Defensive State (DND)')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 20597, 'Sword Specialization')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 20598, 'The Human Spirit')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 20599, 'Diplomacy')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 20600, 'Perception')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 20864, 'Mace Specialization')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 21184, 'Rogue Passive (DND)')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 21651, 'Opening')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 21652, 'Closing')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 22027, 'Remove Insignia')
    ,(@RACE_HUMAN, @CLASS_ROGUE, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_HUMAN, @CLASS_PRIEST, 81, 'Dodge')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 198, 'One-Handed Maces')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 203, 'Unarmed')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 204, 'Defense')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 585, 'Smite')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 668, 'Language Common')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 2050, 'Lesser Heal')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 2382, 'Generic')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 2479, 'Honorless Target')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 3050, 'Detect')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 3365, 'Opening')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 5009, 'Wands')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 5019, 'Shoot')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 6233, 'Closing')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 6246, 'Closing')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 6247, 'Opening')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 6477, 'Opening')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 6478, 'Opening')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 6603, 'Attack')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 7266, 'Duel')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 7267, 'Grovel')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 7355, 'Stuck')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 8386, 'Attacking')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 9078, 'Cloth')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 9125, 'Generic')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 20597, 'Sword Specialization')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 20598, 'The Human Spirit')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 20599, 'Diplomacy')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 20600, 'Perception')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 20864, 'Mace Specialization')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 21651, 'Opening')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 21652, 'Closing')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 22027, 'Remove Insignia')
    ,(@RACE_HUMAN, @CLASS_PRIEST, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_HUMAN, @CLASS_MAGE, 81, 'Dodge')
    ,(@RACE_HUMAN, @CLASS_MAGE, 133, 'Fireball')
    ,(@RACE_HUMAN, @CLASS_MAGE, 168, 'Frost Armor')
    ,(@RACE_HUMAN, @CLASS_MAGE, 203, 'Unarmed')
    ,(@RACE_HUMAN, @CLASS_MAGE, 204, 'Defense')
    ,(@RACE_HUMAN, @CLASS_MAGE, 227, 'Staves')
    ,(@RACE_HUMAN, @CLASS_MAGE, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_HUMAN, @CLASS_MAGE, 668, 'Language Common')
    ,(@RACE_HUMAN, @CLASS_MAGE, 2382, 'Generic')
    ,(@RACE_HUMAN, @CLASS_MAGE, 2479, 'Honorless Target')
    ,(@RACE_HUMAN, @CLASS_MAGE, 3050, 'Detect')
    ,(@RACE_HUMAN, @CLASS_MAGE, 3365, 'Opening')
    ,(@RACE_HUMAN, @CLASS_MAGE, 5009, 'Wands')
    ,(@RACE_HUMAN, @CLASS_MAGE, 5019, 'Shoot')
    ,(@RACE_HUMAN, @CLASS_MAGE, 6233, 'Closing')
    ,(@RACE_HUMAN, @CLASS_MAGE, 6246, 'Closing')
    ,(@RACE_HUMAN, @CLASS_MAGE, 6247, 'Opening')
    ,(@RACE_HUMAN, @CLASS_MAGE, 6477, 'Opening')
    ,(@RACE_HUMAN, @CLASS_MAGE, 6478, 'Opening')
    ,(@RACE_HUMAN, @CLASS_MAGE, 6603, 'Attack')
    ,(@RACE_HUMAN, @CLASS_MAGE, 7266, 'Duel')
    ,(@RACE_HUMAN, @CLASS_MAGE, 7267, 'Grovel')
    ,(@RACE_HUMAN, @CLASS_MAGE, 7355, 'Stuck')
    ,(@RACE_HUMAN, @CLASS_MAGE, 8386, 'Attacking')
    ,(@RACE_HUMAN, @CLASS_MAGE, 9078, 'Cloth')
    ,(@RACE_HUMAN, @CLASS_MAGE, 9125, 'Generic')
    ,(@RACE_HUMAN, @CLASS_MAGE, 20597, 'Sword Specialization')
    ,(@RACE_HUMAN, @CLASS_MAGE, 20598, 'The Human Spirit')
    ,(@RACE_HUMAN, @CLASS_MAGE, 20599, 'Diplomacy')
    ,(@RACE_HUMAN, @CLASS_MAGE, 20600, 'Perception')
    ,(@RACE_HUMAN, @CLASS_MAGE, 20864, 'Mace Specialization')
    ,(@RACE_HUMAN, @CLASS_MAGE, 21651, 'Opening')
    ,(@RACE_HUMAN, @CLASS_MAGE, 21652, 'Closing')
    ,(@RACE_HUMAN, @CLASS_MAGE, 22027, 'Remove Insignia')
    ,(@RACE_HUMAN, @CLASS_MAGE, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_HUMAN, @CLASS_WARLOCK, 81, 'Dodge')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 203, 'Unarmed')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 204, 'Defense')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 668, 'Language Common')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 686, 'Shadow Bolt')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 687, 'Demon Skin')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 1180, 'Daggers')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 2382, 'Generic')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 2479, 'Honorless Target')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 3050, 'Detect')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 3365, 'Opening')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 5009, 'Wands')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 5019, 'Shoot')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 6233, 'Closing')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 6246, 'Closing')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 6247, 'Opening')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 6477, 'Opening')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 6478, 'Opening')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 6603, 'Attack')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 7266, 'Duel')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 7267, 'Grovel')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 7355, 'Stuck')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 8386, 'Attacking')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 9078, 'Cloth')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 9125, 'Generic')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 20597, 'Sword Specialization')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 20598, 'The Human Spirit')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 20599, 'Diplomacy')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 20600, 'Perception')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 20864, 'Mace Specialization')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 21651, 'Opening')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 21652, 'Closing')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 22027, 'Remove Insignia')
    ,(@RACE_HUMAN, @CLASS_WARLOCK, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_ORC, @CLASS_WARRIOR, 78, 'Heroic Strike')
    ,(@RACE_ORC, @CLASS_WARRIOR, 81, 'Dodge')
    ,(@RACE_ORC, @CLASS_WARRIOR, 107, 'Block')
    ,(@RACE_ORC, @CLASS_WARRIOR, 196, 'One-Handed Axes')
    ,(@RACE_ORC, @CLASS_WARRIOR, 197, 'Two-Handed Axes')
    ,(@RACE_ORC, @CLASS_WARRIOR, 201, 'One-Handed Swords')
    ,(@RACE_ORC, @CLASS_WARRIOR, 203, 'Unarmed')
    ,(@RACE_ORC, @CLASS_WARRIOR, 204, 'Defense')
    ,(@RACE_ORC, @CLASS_WARRIOR, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_ORC, @CLASS_WARRIOR, 669, 'Language Orcish')
    ,(@RACE_ORC, @CLASS_WARRIOR, 2382, 'Generic')
    ,(@RACE_ORC, @CLASS_WARRIOR, 2457, 'Battle Stance')
    ,(@RACE_ORC, @CLASS_WARRIOR, 2479, 'Honorless Target')
    ,(@RACE_ORC, @CLASS_WARRIOR, 3050, 'Detect')
    ,(@RACE_ORC, @CLASS_WARRIOR, 3365, 'Opening')
    ,(@RACE_ORC, @CLASS_WARRIOR, 5301, 'Defensive State (DND)')
    ,(@RACE_ORC, @CLASS_WARRIOR, 6233, 'Closing')
    ,(@RACE_ORC, @CLASS_WARRIOR, 6246, 'Closing')
    ,(@RACE_ORC, @CLASS_WARRIOR, 6247, 'Opening')
    ,(@RACE_ORC, @CLASS_WARRIOR, 6477, 'Opening')
    ,(@RACE_ORC, @CLASS_WARRIOR, 6478, 'Opening')
    ,(@RACE_ORC, @CLASS_WARRIOR, 6603, 'Attack')
    ,(@RACE_ORC, @CLASS_WARRIOR, 7266, 'Duel')
    ,(@RACE_ORC, @CLASS_WARRIOR, 7267, 'Grovel')
    ,(@RACE_ORC, @CLASS_WARRIOR, 7355, 'Stuck')
    ,(@RACE_ORC, @CLASS_WARRIOR, 8386, 'Attacking')
    ,(@RACE_ORC, @CLASS_WARRIOR, 8737, 'Mail')
    ,(@RACE_ORC, @CLASS_WARRIOR, 9077, 'Leather')
    ,(@RACE_ORC, @CLASS_WARRIOR, 9078, 'Cloth')
    ,(@RACE_ORC, @CLASS_WARRIOR, 9116, 'Shield')
    ,(@RACE_ORC, @CLASS_WARRIOR, 9125, 'Generic')
    ,(@RACE_ORC, @CLASS_WARRIOR, 20572, 'Blood Fury')
    ,(@RACE_ORC, @CLASS_WARRIOR, 20573, 'Hardiness')
    ,(@RACE_ORC, @CLASS_WARRIOR, 20574, 'Axe Specialization')
    ,(@RACE_ORC, @CLASS_WARRIOR, 21563, 'Command')
    ,(@RACE_ORC, @CLASS_WARRIOR, 21651, 'Opening')
    ,(@RACE_ORC, @CLASS_WARRIOR, 21652, 'Closing')
    ,(@RACE_ORC, @CLASS_WARRIOR, 22027, 'Remove Insignia')
    ,(@RACE_ORC, @CLASS_WARRIOR, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_ORC, @CLASS_HUNTER, 75, 'Auto Shot')
    ,(@RACE_ORC, @CLASS_HUNTER, 81, 'Dodge')
    ,(@RACE_ORC, @CLASS_HUNTER, 196, 'One-Handed Axes')
    ,(@RACE_ORC, @CLASS_HUNTER, 203, 'Unarmed')
    ,(@RACE_ORC, @CLASS_HUNTER, 204, 'Defense')
    ,(@RACE_ORC, @CLASS_HUNTER, 264, 'Bows')
    ,(@RACE_ORC, @CLASS_HUNTER, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_ORC, @CLASS_HUNTER, 669, 'Language Orcish')
    ,(@RACE_ORC, @CLASS_HUNTER, 2382, 'Generic')
    ,(@RACE_ORC, @CLASS_HUNTER, 2479, 'Honorless Target')
    ,(@RACE_ORC, @CLASS_HUNTER, 2973, 'Raptor Strike')
    ,(@RACE_ORC, @CLASS_HUNTER, 3050, 'Detect')
    ,(@RACE_ORC, @CLASS_HUNTER, 3365, 'Opening')
    ,(@RACE_ORC, @CLASS_HUNTER, 6233, 'Closing')
    ,(@RACE_ORC, @CLASS_HUNTER, 6246, 'Closing')
    ,(@RACE_ORC, @CLASS_HUNTER, 6247, 'Opening')
    ,(@RACE_ORC, @CLASS_HUNTER, 6477, 'Opening')
    ,(@RACE_ORC, @CLASS_HUNTER, 6478, 'Opening')
    ,(@RACE_ORC, @CLASS_HUNTER, 6603, 'Attack')
    ,(@RACE_ORC, @CLASS_HUNTER, 7266, 'Duel')
    ,(@RACE_ORC, @CLASS_HUNTER, 7267, 'Grovel')
    ,(@RACE_ORC, @CLASS_HUNTER, 7355, 'Stuck')
    ,(@RACE_ORC, @CLASS_HUNTER, 8386, 'Attacking')
    ,(@RACE_ORC, @CLASS_HUNTER, 9077, 'Leather')
    ,(@RACE_ORC, @CLASS_HUNTER, 9078, 'Cloth')
    ,(@RACE_ORC, @CLASS_HUNTER, 9125, 'Generic')
    ,(@RACE_ORC, @CLASS_HUNTER, 13358, 'Defensive State (DND)')
    ,(@RACE_ORC, @CLASS_HUNTER, 20572, 'Blood Fury')
    ,(@RACE_ORC, @CLASS_HUNTER, 20573, 'Hardiness')
    ,(@RACE_ORC, @CLASS_HUNTER, 20574, 'Axe Specialization')
    ,(@RACE_ORC, @CLASS_HUNTER, 20576, 'Command')
    ,(@RACE_ORC, @CLASS_HUNTER, 21651, 'Opening')
    ,(@RACE_ORC, @CLASS_HUNTER, 21652, 'Closing')
    ,(@RACE_ORC, @CLASS_HUNTER, 22027, 'Remove Insignia')
    ,(@RACE_ORC, @CLASS_HUNTER, 22810, 'Opening - No Text')
    ,(@RACE_ORC, @CLASS_HUNTER, 24949, 'Defensive State 2 (DND)')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_ORC, @CLASS_ROGUE, 81, 'Dodge')
    ,(@RACE_ORC, @CLASS_ROGUE, 203, 'Unarmed')
    ,(@RACE_ORC, @CLASS_ROGUE, 204, 'Defense')
    ,(@RACE_ORC, @CLASS_ROGUE, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_ORC, @CLASS_ROGUE, 669, 'Language Orcish')
    ,(@RACE_ORC, @CLASS_ROGUE, 1180, 'Daggers')
    ,(@RACE_ORC, @CLASS_ROGUE, 1752, 'Sinister Strike')
    ,(@RACE_ORC, @CLASS_ROGUE, 2098, 'Eviscerate')
    ,(@RACE_ORC, @CLASS_ROGUE, 2382, 'Generic')
    ,(@RACE_ORC, @CLASS_ROGUE, 2479, 'Honorless Target')
    ,(@RACE_ORC, @CLASS_ROGUE, 2567, 'Thrown')
    ,(@RACE_ORC, @CLASS_ROGUE, 2764, 'Throw')
    ,(@RACE_ORC, @CLASS_ROGUE, 3050, 'Detect')
    ,(@RACE_ORC, @CLASS_ROGUE, 3365, 'Opening')
    ,(@RACE_ORC, @CLASS_ROGUE, 6233, 'Closing')
    ,(@RACE_ORC, @CLASS_ROGUE, 6246, 'Closing')
    ,(@RACE_ORC, @CLASS_ROGUE, 6247, 'Opening')
    ,(@RACE_ORC, @CLASS_ROGUE, 6477, 'Opening')
    ,(@RACE_ORC, @CLASS_ROGUE, 6478, 'Opening')
    ,(@RACE_ORC, @CLASS_ROGUE, 6603, 'Attack')
    ,(@RACE_ORC, @CLASS_ROGUE, 7266, 'Duel')
    ,(@RACE_ORC, @CLASS_ROGUE, 7267, 'Grovel')
    ,(@RACE_ORC, @CLASS_ROGUE, 7355, 'Stuck')
    ,(@RACE_ORC, @CLASS_ROGUE, 8386, 'Attacking')
    ,(@RACE_ORC, @CLASS_ROGUE, 9077, 'Leather')
    ,(@RACE_ORC, @CLASS_ROGUE, 9078, 'Cloth')
    ,(@RACE_ORC, @CLASS_ROGUE, 9125, 'Generic')
    ,(@RACE_ORC, @CLASS_ROGUE, 16092, 'Defensive State (DND)')
    ,(@RACE_ORC, @CLASS_ROGUE, 20572, 'Blood Fury')
    ,(@RACE_ORC, @CLASS_ROGUE, 20573, 'Hardiness')
    ,(@RACE_ORC, @CLASS_ROGUE, 20574, 'Axe Specialization')
    ,(@RACE_ORC, @CLASS_ROGUE, 21184, 'Rogue Passive (DND)')
    ,(@RACE_ORC, @CLASS_ROGUE, 21563, 'Command')
    ,(@RACE_ORC, @CLASS_ROGUE, 21651, 'Opening')
    ,(@RACE_ORC, @CLASS_ROGUE, 21652, 'Closing')
    ,(@RACE_ORC, @CLASS_ROGUE, 22027, 'Remove Insignia')
    ,(@RACE_ORC, @CLASS_ROGUE, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_ORC, @CLASS_SHAMAN, 81, 'Dodge')
    ,(@RACE_ORC, @CLASS_SHAMAN, 107, 'Block')
    ,(@RACE_ORC, @CLASS_SHAMAN, 198, 'One-Handed Maces')
    ,(@RACE_ORC, @CLASS_SHAMAN, 203, 'Unarmed')
    ,(@RACE_ORC, @CLASS_SHAMAN, 204, 'Defense')
    ,(@RACE_ORC, @CLASS_SHAMAN, 227, 'Staves')
    ,(@RACE_ORC, @CLASS_SHAMAN, 331, 'Healing Wave')
    ,(@RACE_ORC, @CLASS_SHAMAN, 403, 'Lightning Bolt')
    ,(@RACE_ORC, @CLASS_SHAMAN, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_ORC, @CLASS_SHAMAN, 669, 'Language Orcish')
    ,(@RACE_ORC, @CLASS_SHAMAN, 2382, 'Generic')
    ,(@RACE_ORC, @CLASS_SHAMAN, 2479, 'Honorless Target')
    ,(@RACE_ORC, @CLASS_SHAMAN, 3050, 'Detect')
    ,(@RACE_ORC, @CLASS_SHAMAN, 3365, 'Opening')
    ,(@RACE_ORC, @CLASS_SHAMAN, 6233, 'Closing')
    ,(@RACE_ORC, @CLASS_SHAMAN, 6246, 'Closing')
    ,(@RACE_ORC, @CLASS_SHAMAN, 6247, 'Opening')
    ,(@RACE_ORC, @CLASS_SHAMAN, 6477, 'Opening')
    ,(@RACE_ORC, @CLASS_SHAMAN, 6478, 'Opening')
    ,(@RACE_ORC, @CLASS_SHAMAN, 6603, 'Attack')
    ,(@RACE_ORC, @CLASS_SHAMAN, 7266, 'Duel')
    ,(@RACE_ORC, @CLASS_SHAMAN, 7267, 'Grovel')
    ,(@RACE_ORC, @CLASS_SHAMAN, 7355, 'Stuck')
    ,(@RACE_ORC, @CLASS_SHAMAN, 8386, 'Attacking')
    ,(@RACE_ORC, @CLASS_SHAMAN, 9077, 'Leather')
    ,(@RACE_ORC, @CLASS_SHAMAN, 9078, 'Cloth')
    ,(@RACE_ORC, @CLASS_SHAMAN, 9116, 'Shield')
    ,(@RACE_ORC, @CLASS_SHAMAN, 9125, 'Generic')
    ,(@RACE_ORC, @CLASS_SHAMAN, 20572, 'Blood Fury')
    ,(@RACE_ORC, @CLASS_SHAMAN, 20573, 'Hardiness')
    ,(@RACE_ORC, @CLASS_SHAMAN, 20574, 'Axe Specialization')
    ,(@RACE_ORC, @CLASS_SHAMAN, 21563, 'Command')
    ,(@RACE_ORC, @CLASS_SHAMAN, 21651, 'Opening')
    ,(@RACE_ORC, @CLASS_SHAMAN, 21652, 'Closing')
    ,(@RACE_ORC, @CLASS_SHAMAN, 22027, 'Remove Insignia')
    ,(@RACE_ORC, @CLASS_SHAMAN, 22810, 'Opening - No Text')
    ,(@RACE_ORC, @CLASS_SHAMAN, 27763, 'Totem')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_ORC, @CLASS_WARLOCK, 81, 'Dodge')
    ,(@RACE_ORC, @CLASS_WARLOCK, 203, 'Unarmed')
    ,(@RACE_ORC, @CLASS_WARLOCK, 204, 'Defense')
    ,(@RACE_ORC, @CLASS_WARLOCK, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_ORC, @CLASS_WARLOCK, 669, 'Language Orcish')
    ,(@RACE_ORC, @CLASS_WARLOCK, 686, 'Shadow Bolt')
    ,(@RACE_ORC, @CLASS_WARLOCK, 687, 'Demon Skin')
    ,(@RACE_ORC, @CLASS_WARLOCK, 1180, 'Daggers')
    ,(@RACE_ORC, @CLASS_WARLOCK, 2382, 'Generic')
    ,(@RACE_ORC, @CLASS_WARLOCK, 2479, 'Honorless Target')
    ,(@RACE_ORC, @CLASS_WARLOCK, 3050, 'Detect')
    ,(@RACE_ORC, @CLASS_WARLOCK, 3365, 'Opening')
    ,(@RACE_ORC, @CLASS_WARLOCK, 5009, 'Wands')
    ,(@RACE_ORC, @CLASS_WARLOCK, 5019, 'Shoot')
    ,(@RACE_ORC, @CLASS_WARLOCK, 6233, 'Closing')
    ,(@RACE_ORC, @CLASS_WARLOCK, 6246, 'Closing')
    ,(@RACE_ORC, @CLASS_WARLOCK, 6247, 'Opening')
    ,(@RACE_ORC, @CLASS_WARLOCK, 6477, 'Opening')
    ,(@RACE_ORC, @CLASS_WARLOCK, 6478, 'Opening')
    ,(@RACE_ORC, @CLASS_WARLOCK, 6603, 'Attack')
    ,(@RACE_ORC, @CLASS_WARLOCK, 7266, 'Duel')
    ,(@RACE_ORC, @CLASS_WARLOCK, 7267, 'Grovel')
    ,(@RACE_ORC, @CLASS_WARLOCK, 7355, 'Stuck')
    ,(@RACE_ORC, @CLASS_WARLOCK, 8386, 'Attacking')
    ,(@RACE_ORC, @CLASS_WARLOCK, 9078, 'Cloth')
    ,(@RACE_ORC, @CLASS_WARLOCK, 9125, 'Generic')
    ,(@RACE_ORC, @CLASS_WARLOCK, 20572, 'Blood Fury')
    ,(@RACE_ORC, @CLASS_WARLOCK, 20573, 'Hardiness')
    ,(@RACE_ORC, @CLASS_WARLOCK, 20574, 'Axe Specialization')
    ,(@RACE_ORC, @CLASS_WARLOCK, 20575, 'Command')
    ,(@RACE_ORC, @CLASS_WARLOCK, 21651, 'Opening')
    ,(@RACE_ORC, @CLASS_WARLOCK, 21652, 'Closing')
    ,(@RACE_ORC, @CLASS_WARLOCK, 22027, 'Remove Insignia')
    ,(@RACE_ORC, @CLASS_WARLOCK, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_DWARF, @CLASS_WARRIOR, 78, 'Heroic Strike')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 81, 'Dodge')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 107, 'Block')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 196, 'One-Handed Axes')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 197, 'Two-Handed Axes')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 198, 'One-Handed Maces')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 203, 'Unarmed')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 204, 'Defense')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 668, 'Language Common')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 672, 'Language Dwarven')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 2382, 'Generic')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 2457, 'Battle Stance')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 2479, 'Honorless Target')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 2481, 'Find Treasure')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 3050, 'Detect')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 3365, 'Opening')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 5301, 'Defensive State (DND)')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 6233, 'Closing')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 6246, 'Closing')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 6247, 'Opening')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 6477, 'Opening')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 6478, 'Opening')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 6603, 'Attack')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 7266, 'Duel')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 7267, 'Grovel')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 7355, 'Stuck')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 8386, 'Attacking')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 8737, 'Mail')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 9077, 'Leather')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 9078, 'Cloth')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 9116, 'Shield')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 9125, 'Generic')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 20594, 'Stoneform')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 20595, 'Gun Specialization')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 20596, 'Frost Resistance')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 21651, 'Opening')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 21652, 'Closing')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 22027, 'Remove Insignia')
    ,(@RACE_DWARF, @CLASS_WARRIOR, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_DWARF, @CLASS_PALADIN, 81, 'Dodge')
    ,(@RACE_DWARF, @CLASS_PALADIN, 107, 'Block')
    ,(@RACE_DWARF, @CLASS_PALADIN, 198, 'One-Handed Maces')
    ,(@RACE_DWARF, @CLASS_PALADIN, 199, 'Two-Handed Maces')
    ,(@RACE_DWARF, @CLASS_PALADIN, 203, 'Unarmed')
    ,(@RACE_DWARF, @CLASS_PALADIN, 204, 'Defense')
    ,(@RACE_DWARF, @CLASS_PALADIN, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_DWARF, @CLASS_PALADIN, 635, 'Holy Light')
    ,(@RACE_DWARF, @CLASS_PALADIN, 668, 'Language Common')
    ,(@RACE_DWARF, @CLASS_PALADIN, 672, 'Language Dwarven')
    ,(@RACE_DWARF, @CLASS_PALADIN, 2382, 'Generic')
    ,(@RACE_DWARF, @CLASS_PALADIN, 2479, 'Honorless Target')
    ,(@RACE_DWARF, @CLASS_PALADIN, 2481, 'Find Treasure')
    ,(@RACE_DWARF, @CLASS_PALADIN, 3050, 'Detect')
    ,(@RACE_DWARF, @CLASS_PALADIN, 3365, 'Opening')
    ,(@RACE_DWARF, @CLASS_PALADIN, 6233, 'Closing')
    ,(@RACE_DWARF, @CLASS_PALADIN, 6246, 'Closing')
    ,(@RACE_DWARF, @CLASS_PALADIN, 6247, 'Opening')
    ,(@RACE_DWARF, @CLASS_PALADIN, 6477, 'Opening')
    ,(@RACE_DWARF, @CLASS_PALADIN, 6478, 'Opening')
    ,(@RACE_DWARF, @CLASS_PALADIN, 6603, 'Attack')
    ,(@RACE_DWARF, @CLASS_PALADIN, 7266, 'Duel')
    ,(@RACE_DWARF, @CLASS_PALADIN, 7267, 'Grovel')
    ,(@RACE_DWARF, @CLASS_PALADIN, 7355, 'Stuck')
    ,(@RACE_DWARF, @CLASS_PALADIN, 8386, 'Attacking')
    ,(@RACE_DWARF, @CLASS_PALADIN, 8737, 'Mail')
    ,(@RACE_DWARF, @CLASS_PALADIN, 9077, 'Leather')
    ,(@RACE_DWARF, @CLASS_PALADIN, 9078, 'Cloth')
    ,(@RACE_DWARF, @CLASS_PALADIN, 9116, 'Shield')
    ,(@RACE_DWARF, @CLASS_PALADIN, 9125, 'Generic')
    ,(@RACE_DWARF, @CLASS_PALADIN, 20594, 'Stoneform')
    ,(@RACE_DWARF, @CLASS_PALADIN, 20595, 'Gun Specialization')
    ,(@RACE_DWARF, @CLASS_PALADIN, 20596, 'Frost Resistance')
    ,(@RACE_DWARF, @CLASS_PALADIN, 21084, 'Seal of Righteousness')
    ,(@RACE_DWARF, @CLASS_PALADIN, 21651, 'Opening')
    ,(@RACE_DWARF, @CLASS_PALADIN, 21652, 'Closing')
    ,(@RACE_DWARF, @CLASS_PALADIN, 22027, 'Remove Insignia')
    ,(@RACE_DWARF, @CLASS_PALADIN, 22810, 'Opening - No Text')
    ,(@RACE_DWARF, @CLASS_PALADIN, 27762, 'Libram')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_DWARF, @CLASS_HUNTER, 75, 'Auto Shot')
    ,(@RACE_DWARF, @CLASS_HUNTER, 81, 'Dodge')
    ,(@RACE_DWARF, @CLASS_HUNTER, 196, 'One-Handed Axes')
    ,(@RACE_DWARF, @CLASS_HUNTER, 203, 'Unarmed')
    ,(@RACE_DWARF, @CLASS_HUNTER, 204, 'Defense')
    ,(@RACE_DWARF, @CLASS_HUNTER, 266, 'Guns')
    ,(@RACE_DWARF, @CLASS_HUNTER, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_DWARF, @CLASS_HUNTER, 668, 'Language Common')
    ,(@RACE_DWARF, @CLASS_HUNTER, 672, 'Language Dwarven')
    ,(@RACE_DWARF, @CLASS_HUNTER, 2382, 'Generic')
    ,(@RACE_DWARF, @CLASS_HUNTER, 2479, 'Honorless Target')
    ,(@RACE_DWARF, @CLASS_HUNTER, 2481, 'Find Treasure')
    ,(@RACE_DWARF, @CLASS_HUNTER, 2973, 'Raptor Strike')
    ,(@RACE_DWARF, @CLASS_HUNTER, 3050, 'Detect')
    ,(@RACE_DWARF, @CLASS_HUNTER, 3365, 'Opening')
    ,(@RACE_DWARF, @CLASS_HUNTER, 6233, 'Closing')
    ,(@RACE_DWARF, @CLASS_HUNTER, 6246, 'Closing')
    ,(@RACE_DWARF, @CLASS_HUNTER, 6247, 'Opening')
    ,(@RACE_DWARF, @CLASS_HUNTER, 6477, 'Opening')
    ,(@RACE_DWARF, @CLASS_HUNTER, 6478, 'Opening')
    ,(@RACE_DWARF, @CLASS_HUNTER, 6603, 'Attack')
    ,(@RACE_DWARF, @CLASS_HUNTER, 7266, 'Duel')
    ,(@RACE_DWARF, @CLASS_HUNTER, 7267, 'Grovel')
    ,(@RACE_DWARF, @CLASS_HUNTER, 7355, 'Stuck')
    ,(@RACE_DWARF, @CLASS_HUNTER, 8386, 'Attacking')
    ,(@RACE_DWARF, @CLASS_HUNTER, 9077, 'Leather')
    ,(@RACE_DWARF, @CLASS_HUNTER, 9078, 'Cloth')
    ,(@RACE_DWARF, @CLASS_HUNTER, 9125, 'Generic')
    ,(@RACE_DWARF, @CLASS_HUNTER, 13358, 'Defensive State (DND)')
    ,(@RACE_DWARF, @CLASS_HUNTER, 20594, 'Stoneform')
    ,(@RACE_DWARF, @CLASS_HUNTER, 20595, 'Gun Specialization')
    ,(@RACE_DWARF, @CLASS_HUNTER, 20596, 'Frost Resistance')
    ,(@RACE_DWARF, @CLASS_HUNTER, 21651, 'Opening')
    ,(@RACE_DWARF, @CLASS_HUNTER, 21652, 'Closing')
    ,(@RACE_DWARF, @CLASS_HUNTER, 22027, 'Remove Insignia')
    ,(@RACE_DWARF, @CLASS_HUNTER, 22810, 'Opening - No Text')
    ,(@RACE_DWARF, @CLASS_HUNTER, 24949, 'Defensive State 2 (DND)')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_DWARF, @CLASS_ROGUE, 81, 'Dodge')
    ,(@RACE_DWARF, @CLASS_ROGUE, 203, 'Unarmed')
    ,(@RACE_DWARF, @CLASS_ROGUE, 204, 'Defense')
    ,(@RACE_DWARF, @CLASS_ROGUE, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_DWARF, @CLASS_ROGUE, 668, 'Language Common')
    ,(@RACE_DWARF, @CLASS_ROGUE, 672, 'Language Dwarven')
    ,(@RACE_DWARF, @CLASS_ROGUE, 1180, 'Daggers')
    ,(@RACE_DWARF, @CLASS_ROGUE, 1752, 'Sinister Strike')
    ,(@RACE_DWARF, @CLASS_ROGUE, 2098, 'Eviscerate')
    ,(@RACE_DWARF, @CLASS_ROGUE, 2382, 'Generic')
    ,(@RACE_DWARF, @CLASS_ROGUE, 2479, 'Honorless Target')
    ,(@RACE_DWARF, @CLASS_ROGUE, 2481, 'Find Treasure')
    ,(@RACE_DWARF, @CLASS_ROGUE, 2567, 'Thrown')
    ,(@RACE_DWARF, @CLASS_ROGUE, 2764, 'Throw')
    ,(@RACE_DWARF, @CLASS_ROGUE, 3050, 'Detect')
    ,(@RACE_DWARF, @CLASS_ROGUE, 3365, 'Opening')
    ,(@RACE_DWARF, @CLASS_ROGUE, 6233, 'Closing')
    ,(@RACE_DWARF, @CLASS_ROGUE, 6246, 'Closing')
    ,(@RACE_DWARF, @CLASS_ROGUE, 6247, 'Opening')
    ,(@RACE_DWARF, @CLASS_ROGUE, 6477, 'Opening')
    ,(@RACE_DWARF, @CLASS_ROGUE, 6478, 'Opening')
    ,(@RACE_DWARF, @CLASS_ROGUE, 6603, 'Attack')
    ,(@RACE_DWARF, @CLASS_ROGUE, 7266, 'Duel')
    ,(@RACE_DWARF, @CLASS_ROGUE, 7267, 'Grovel')
    ,(@RACE_DWARF, @CLASS_ROGUE, 7355, 'Stuck')
    ,(@RACE_DWARF, @CLASS_ROGUE, 8386, 'Attacking')
    ,(@RACE_DWARF, @CLASS_ROGUE, 9077, 'Leather')
    ,(@RACE_DWARF, @CLASS_ROGUE, 9078, 'Cloth')
    ,(@RACE_DWARF, @CLASS_ROGUE, 9125, 'Generic')
    ,(@RACE_DWARF, @CLASS_ROGUE, 16092, 'Defensive State (DND)')
    ,(@RACE_DWARF, @CLASS_ROGUE, 20594, 'Stoneform')
    ,(@RACE_DWARF, @CLASS_ROGUE, 20595, 'Gun Specialization')
    ,(@RACE_DWARF, @CLASS_ROGUE, 20596, 'Frost Resistance')
    ,(@RACE_DWARF, @CLASS_ROGUE, 21184, 'Rogue Passive (DND)')
    ,(@RACE_DWARF, @CLASS_ROGUE, 21651, 'Opening')
    ,(@RACE_DWARF, @CLASS_ROGUE, 21652, 'Closing')
    ,(@RACE_DWARF, @CLASS_ROGUE, 22027, 'Remove Insignia')
    ,(@RACE_DWARF, @CLASS_ROGUE, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_DWARF, @CLASS_PRIEST, 81, 'Dodge')
    ,(@RACE_DWARF, @CLASS_PRIEST, 198, 'One-Handed Maces')
    ,(@RACE_DWARF, @CLASS_PRIEST, 203, 'Unarmed')
    ,(@RACE_DWARF, @CLASS_PRIEST, 204, 'Defense')
    ,(@RACE_DWARF, @CLASS_PRIEST, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_DWARF, @CLASS_PRIEST, 585, 'Smite')
    ,(@RACE_DWARF, @CLASS_PRIEST, 668, 'Language Common')
    ,(@RACE_DWARF, @CLASS_PRIEST, 672, 'Language Dwarven')
    ,(@RACE_DWARF, @CLASS_PRIEST, 2050, 'Lesser Heal')
    ,(@RACE_DWARF, @CLASS_PRIEST, 2382, 'Generic')
    ,(@RACE_DWARF, @CLASS_PRIEST, 2479, 'Honorless Target')
    ,(@RACE_DWARF, @CLASS_PRIEST, 2481, 'Find Treasure')
    ,(@RACE_DWARF, @CLASS_PRIEST, 3050, 'Detect')
    ,(@RACE_DWARF, @CLASS_PRIEST, 3365, 'Opening')
    ,(@RACE_DWARF, @CLASS_PRIEST, 5009, 'Wands')
    ,(@RACE_DWARF, @CLASS_PRIEST, 5019, 'Shoot')
    ,(@RACE_DWARF, @CLASS_PRIEST, 6233, 'Closing')
    ,(@RACE_DWARF, @CLASS_PRIEST, 6246, 'Closing')
    ,(@RACE_DWARF, @CLASS_PRIEST, 6247, 'Opening')
    ,(@RACE_DWARF, @CLASS_PRIEST, 6477, 'Opening')
    ,(@RACE_DWARF, @CLASS_PRIEST, 6478, 'Opening')
    ,(@RACE_DWARF, @CLASS_PRIEST, 6603, 'Attack')
    ,(@RACE_DWARF, @CLASS_PRIEST, 7266, 'Duel')
    ,(@RACE_DWARF, @CLASS_PRIEST, 7267, 'Grovel')
    ,(@RACE_DWARF, @CLASS_PRIEST, 7355, 'Stuck')
    ,(@RACE_DWARF, @CLASS_PRIEST, 8386, 'Attacking')
    ,(@RACE_DWARF, @CLASS_PRIEST, 9078, 'Cloth')
    ,(@RACE_DWARF, @CLASS_PRIEST, 9125, 'Generic')
    ,(@RACE_DWARF, @CLASS_PRIEST, 20594, 'Stoneform')
    ,(@RACE_DWARF, @CLASS_PRIEST, 20595, 'Gun Specialization')
    ,(@RACE_DWARF, @CLASS_PRIEST, 20596, 'Frost Resistance')
    ,(@RACE_DWARF, @CLASS_PRIEST, 21651, 'Opening')
    ,(@RACE_DWARF, @CLASS_PRIEST, 21652, 'Closing')
    ,(@RACE_DWARF, @CLASS_PRIEST, 22027, 'Remove Insignia')
    ,(@RACE_DWARF, @CLASS_PRIEST, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_NIGHT_ELF, @CLASS_WARRIOR, 78, 'Heroic Strike')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 81, 'Dodge')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 107, 'Block')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 198, 'One-Handed Maces')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 201, 'One-Handed Swords')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 203, 'Unarmed')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 204, 'Defense')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 668, 'Language Common')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 671, 'Language Darnassian')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 1180, 'Daggers')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 2382, 'Generic')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 2457, 'Battle Stance')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 2479, 'Honorless Target')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 3050, 'Detect')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 3365, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 5301, 'Defensive State (DND)')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 6233, 'Closing')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 6246, 'Closing')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 6247, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 6477, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 6478, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 6603, 'Attack')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 7266, 'Duel')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 7267, 'Grovel')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 7355, 'Stuck')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 8386, 'Attacking')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 8737, 'Mail')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 9077, 'Leather')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 9078, 'Cloth')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 9116, 'Shield')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 9125, 'Generic')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 20580, 'Shadowmeld')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 20582, 'Quickness')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 20583, 'Nature Resistance')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 20585, 'Wisp Spirit')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 21009, 'Shadowmeld Passive')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 21651, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 21652, 'Closing')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 22027, 'Remove Insignia')
    ,(@RACE_NIGHT_ELF, @CLASS_WARRIOR, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_NIGHT_ELF, @CLASS_HUNTER, 75, 'Auto Shot')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 81, 'Dodge')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 203, 'Unarmed')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 204, 'Defense')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 264, 'Bows')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 668, 'Language Common')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 671, 'Language Darnassian')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 1180, 'Daggers')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 2382, 'Generic')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 2479, 'Honorless Target')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 2973, 'Raptor Strike')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 3050, 'Detect')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 3365, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 6233, 'Closing')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 6246, 'Closing')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 6247, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 6477, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 6478, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 6603, 'Attack')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 7266, 'Duel')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 7267, 'Grovel')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 7355, 'Stuck')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 8386, 'Attacking')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 9077, 'Leather')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 9078, 'Cloth')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 9125, 'Generic')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 13358, 'Defensive State (DND)')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 20580, 'Shadowmeld')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 20582, 'Quickness')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 20583, 'Nature Resistance')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 20585, 'Wisp Spirit')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 21009, 'Shadowmeld Passive')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 21651, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 21652, 'Closing')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 22027, 'Remove Insignia')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 22810, 'Opening - No Text')
    ,(@RACE_NIGHT_ELF, @CLASS_HUNTER, 24949, 'Defensive State 2 (DND)')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_NIGHT_ELF, @CLASS_ROGUE, 81, 'Dodge')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 203, 'Unarmed')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 204, 'Defense')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 668, 'Language Common')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 671, 'Language Darnassian')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 1180, 'Daggers')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 1752, 'Sinister Strike')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 2098, 'Eviscerate')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 2382, 'Generic')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 2479, 'Honorless Target')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 2567, 'Thrown')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 2764, 'Throw')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 3050, 'Detect')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 3365, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 6233, 'Closing')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 6246, 'Closing')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 6247, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 6477, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 6478, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 6603, 'Attack')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 7266, 'Duel')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 7267, 'Grovel')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 7355, 'Stuck')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 8386, 'Attacking')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 9077, 'Leather')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 9078, 'Cloth')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 9125, 'Generic')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 16092, 'Defensive State (DND)')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 20580, 'Shadowmeld')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 20582, 'Quickness')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 20583, 'Nature Resistance')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 20585, 'Wisp Spirit')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 21009, 'Shadowmeld Passive')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 21184, 'Rogue Passive (DND)')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 21651, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 21652, 'Closing')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 22027, 'Remove Insignia')
    ,(@RACE_NIGHT_ELF, @CLASS_ROGUE, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_NIGHT_ELF, @CLASS_PRIEST, 81, 'Dodge')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 198, 'One-Handed Maces')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 203, 'Unarmed')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 204, 'Defense')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 585, 'Smite')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 668, 'Language Common')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 671, 'Language Darnassian')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 2050, 'Lesser Heal')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 2382, 'Generic')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 2479, 'Honorless Target')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 3050, 'Detect')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 3365, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 5009, 'Wands')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 5019, 'Shoot')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 6233, 'Closing')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 6246, 'Closing')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 6247, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 6477, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 6478, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 6603, 'Attack')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 7266, 'Duel')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 7267, 'Grovel')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 7355, 'Stuck')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 8386, 'Attacking')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 9078, 'Cloth')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 9125, 'Generic')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 20580, 'Shadowmeld')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 20582, 'Quickness')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 20583, 'Nature Resistance')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 20585, 'Wisp Spirit')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 21009, 'Shadowmeld Passive')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 21651, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 21652, 'Closing')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 22027, 'Remove Insignia')
    ,(@RACE_NIGHT_ELF, @CLASS_PRIEST, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_NIGHT_ELF, @CLASS_DRUID, 81, 'Dodge')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 203, 'Unarmed')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 204, 'Defense')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 227, 'Staves')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 668, 'Language Common')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 671, 'Language Darnassian')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 1180, 'Daggers')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 2382, 'Generic')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 2479, 'Honorless Target')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 3050, 'Detect')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 3365, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 5176, 'Wrath')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 5185, 'Healing Touch')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 6233, 'Closing')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 6246, 'Closing')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 6247, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 6477, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 6478, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 6603, 'Attack')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 7266, 'Duel')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 7267, 'Grovel')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 7355, 'Stuck')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 8386, 'Attacking')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 9077, 'Leather')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 9078, 'Cloth')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 9125, 'Generic')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 20580, 'Shadowmeld')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 20582, 'Quickness')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 20583, 'Nature Resistance')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 20585, 'Wisp Spirit')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 21009, 'Shadowmeld Passive')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 21651, 'Opening')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 21652, 'Closing')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 22027, 'Remove Insignia')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 22810, 'Opening - No Text')
    ,(@RACE_NIGHT_ELF, @CLASS_DRUID, 27764, 'Fetish')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_UNDEAD, @CLASS_WARRIOR, 78, 'Heroic Strike')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 81, 'Dodge')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 107, 'Block')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 201, 'One-Handed Swords')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 202, 'Two-Handed Swords')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 203, 'Unarmed')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 204, 'Defense')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 669, 'Language Orcish')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 1180, 'Daggers')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 2382, 'Generic')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 2457, 'Battle Stance')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 2479, 'Honorless Target')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 3050, 'Detect')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 3365, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 5227, 'Underwater Breathing')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 5301, 'Defensive State (DND)')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 6233, 'Closing')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 6246, 'Closing')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 6247, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 6477, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 6478, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 6603, 'Attack')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 7266, 'Duel')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 7267, 'Grovel')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 7355, 'Stuck')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 7744, 'Will of the Forsaken')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 8386, 'Attacking')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 8737, 'Mail')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 9077, 'Leather')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 9078, 'Cloth')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 9116, 'Shield')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 9125, 'Generic')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 17737, 'Language Gutterspeak')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 20577, 'Cannibalize')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 20579, 'Shadow Resistance')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 21651, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 21652, 'Closing')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 22027, 'Remove Insignia')
    ,(@RACE_UNDEAD, @CLASS_WARRIOR, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_UNDEAD, @CLASS_ROGUE, 81, 'Dodge')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 203, 'Unarmed')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 204, 'Defense')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 669, 'Language Orcish')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 1180, 'Daggers')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 1752, 'Sinister Strike')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 2098, 'Eviscerate')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 2382, 'Generic')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 2479, 'Honorless Target')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 2567, 'Thrown')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 2764, 'Throw')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 3050, 'Detect')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 3365, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 5227, 'Underwater Breathing')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 6233, 'Closing')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 6246, 'Closing')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 6247, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 6477, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 6478, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 6603, 'Attack')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 7266, 'Duel')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 7267, 'Grovel')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 7355, 'Stuck')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 7744, 'Will of the Forsaken')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 8386, 'Attacking')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 9077, 'Leather')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 9078, 'Cloth')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 9125, 'Generic')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 16092, 'Defensive State (DND)')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 17737, 'Language Gutterspeak')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 20577, 'Cannibalize')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 20579, 'Shadow Resistance')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 21184, 'Rogue Passive (DND)')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 21651, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 21652, 'Closing')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 22027, 'Remove Insignia')
    ,(@RACE_UNDEAD, @CLASS_ROGUE, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_UNDEAD, @CLASS_PRIEST, 81, 'Dodge')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 198, 'One-Handed Maces')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 203, 'Unarmed')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 204, 'Defense')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 585, 'Smite')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 669, 'Language Orcish')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 2050, 'Lesser Heal')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 2382, 'Generic')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 2479, 'Honorless Target')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 3050, 'Detect')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 3365, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 5009, 'Wands')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 5019, 'Shoot')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 5227, 'Underwater Breathing')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 6233, 'Closing')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 6246, 'Closing')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 6247, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 6477, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 6478, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 6603, 'Attack')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 7266, 'Duel')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 7267, 'Grovel')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 7355, 'Stuck')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 7744, 'Will of the Forsaken')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 8386, 'Attacking')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 9078, 'Cloth')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 9125, 'Generic')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 17737, 'Language Gutterspeak')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 20577, 'Cannibalize')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 20579, 'Shadow Resistance')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 21651, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 21652, 'Closing')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 22027, 'Remove Insignia')
    ,(@RACE_UNDEAD, @CLASS_PRIEST, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_UNDEAD, @CLASS_MAGE, 81, 'Dodge')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 133, 'Fireball')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 168, 'Frost Armor')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 203, 'Unarmed')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 204, 'Defense')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 227, 'Staves')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 669, 'Language Orcish')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 2382, 'Generic')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 2479, 'Honorless Target')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 3050, 'Detect')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 3365, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 5009, 'Wands')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 5019, 'Shoot')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 5227, 'Underwater Breathing')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 6233, 'Closing')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 6246, 'Closing')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 6247, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 6477, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 6478, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 6603, 'Attack')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 7266, 'Duel')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 7267, 'Grovel')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 7355, 'Stuck')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 7744, 'Will of the Forsaken')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 8386, 'Attacking')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 9078, 'Cloth')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 9125, 'Generic')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 17737, 'Language Gutterspeak')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 20577, 'Cannibalize')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 20579, 'Shadow Resistance')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 21651, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 21652, 'Closing')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 22027, 'Remove Insignia')
    ,(@RACE_UNDEAD, @CLASS_MAGE, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_UNDEAD, @CLASS_WARLOCK, 81, 'Dodge')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 203, 'Unarmed')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 204, 'Defense')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 669, 'Language Orcish')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 686, 'Shadow Bolt')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 687, 'Demon Skin')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 1180, 'Daggers')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 2382, 'Generic')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 2479, 'Honorless Target')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 3050, 'Detect')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 3365, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 5009, 'Wands')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 5019, 'Shoot')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 5227, 'Underwater Breathing')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 6233, 'Closing')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 6246, 'Closing')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 6247, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 6477, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 6478, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 6603, 'Attack')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 7266, 'Duel')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 7267, 'Grovel')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 7355, 'Stuck')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 7744, 'Will of the Forsaken')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 8386, 'Attacking')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 9078, 'Cloth')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 9125, 'Generic')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 17737, 'Language Gutterspeak')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 20577, 'Cannibalize')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 20579, 'Shadow Resistance')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 21651, 'Opening')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 21652, 'Closing')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 22027, 'Remove Insignia')
    ,(@RACE_UNDEAD, @CLASS_WARLOCK, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_TAUREN, @CLASS_WARRIOR, 78, 'Heroic Strike')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 81, 'Dodge')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 107, 'Block')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 196, 'One-Handed Axes')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 198, 'One-Handed Maces')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 199, 'Two-Handed Maces')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 203, 'Unarmed')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 204, 'Defense')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 669, 'Language Orcish')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 670, 'Language Taurahe')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 2382, 'Generic')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 2457, 'Battle Stance')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 2479, 'Honorless Target')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 3050, 'Detect')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 3365, 'Opening')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 5301, 'Defensive State (DND)')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 6233, 'Closing')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 6246, 'Closing')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 6247, 'Opening')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 6477, 'Opening')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 6478, 'Opening')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 6603, 'Attack')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 7266, 'Duel')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 7267, 'Grovel')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 7355, 'Stuck')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 8386, 'Attacking')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 8737, 'Mail')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 9077, 'Leather')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 9078, 'Cloth')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 9116, 'Shield')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 9125, 'Generic')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 20549, 'War Stomp')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 20550, 'Endurance')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 20551, 'Nature Resistance')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 20552, 'Cultivation')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 21651, 'Opening')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 21652, 'Closing')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 22027, 'Remove Insignia')
    ,(@RACE_TAUREN, @CLASS_WARRIOR, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_TAUREN, @CLASS_HUNTER, 75, 'Auto Shot')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 81, 'Dodge')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 196, 'One-Handed Axes')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 203, 'Unarmed')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 204, 'Defense')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 266, 'Guns')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 669, 'Language Orcish')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 670, 'Language Taurahe')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 2382, 'Generic')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 2479, 'Honorless Target')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 2973, 'Raptor Strike')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 3050, 'Detect')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 3365, 'Opening')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 6233, 'Closing')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 6246, 'Closing')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 6247, 'Opening')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 6477, 'Opening')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 6478, 'Opening')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 6603, 'Attack')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 7266, 'Duel')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 7267, 'Grovel')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 7355, 'Stuck')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 8386, 'Attacking')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 9077, 'Leather')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 9078, 'Cloth')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 9125, 'Generic')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 13358, 'Defensive State (DND)')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 20549, 'War Stomp')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 20550, 'Endurance')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 20551, 'Nature Resistance')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 20552, 'Cultivation')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 21651, 'Opening')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 21652, 'Closing')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 22027, 'Remove Insignia')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 22810, 'Opening - No Text')
    ,(@RACE_TAUREN, @CLASS_HUNTER, 24949, 'Defensive State 2 (DND)')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_TAUREN, @CLASS_SHAMAN, 81, 'Dodge')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 107, 'Block')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 198, 'One-Handed Maces')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 203, 'Unarmed')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 204, 'Defense')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 227, 'Staves')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 331, 'Healing Wave')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 403, 'Lightning Bolt')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 669, 'Language Orcish')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 670, 'Language Taurahe')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 2382, 'Generic')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 2479, 'Honorless Target')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 3050, 'Detect')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 3365, 'Opening')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 6233, 'Closing')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 6246, 'Closing')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 6247, 'Opening')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 6477, 'Opening')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 6478, 'Opening')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 6603, 'Attack')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 7266, 'Duel')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 7267, 'Grovel')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 7355, 'Stuck')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 8386, 'Attacking')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 9077, 'Leather')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 9078, 'Cloth')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 9116, 'Shield')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 9125, 'Generic')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 20549, 'War Stomp')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 20550, 'Endurance')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 20551, 'Nature Resistance')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 20552, 'Cultivation')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 21651, 'Opening')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 21652, 'Closing')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 22027, 'Remove Insignia')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 22810, 'Opening - No Text')
    ,(@RACE_TAUREN, @CLASS_SHAMAN, 27763, 'Totem')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_TAUREN, @CLASS_DRUID, 81, 'Dodge')
    ,(@RACE_TAUREN, @CLASS_DRUID, 198, 'One-Handed Maces')
    ,(@RACE_TAUREN, @CLASS_DRUID, 203, 'Unarmed')
    ,(@RACE_TAUREN, @CLASS_DRUID, 204, 'Defense')
    ,(@RACE_TAUREN, @CLASS_DRUID, 227, 'Staves')
    ,(@RACE_TAUREN, @CLASS_DRUID, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_TAUREN, @CLASS_DRUID, 669, 'Language Orcish')
    ,(@RACE_TAUREN, @CLASS_DRUID, 670, 'Language Taurahe')
    ,(@RACE_TAUREN, @CLASS_DRUID, 2382, 'Generic')
    ,(@RACE_TAUREN, @CLASS_DRUID, 2479, 'Honorless Target')
    ,(@RACE_TAUREN, @CLASS_DRUID, 3050, 'Detect')
    ,(@RACE_TAUREN, @CLASS_DRUID, 3365, 'Opening')
    ,(@RACE_TAUREN, @CLASS_DRUID, 5176, 'Wrath')
    ,(@RACE_TAUREN, @CLASS_DRUID, 5185, 'Healing Touch')
    ,(@RACE_TAUREN, @CLASS_DRUID, 6233, 'Closing')
    ,(@RACE_TAUREN, @CLASS_DRUID, 6246, 'Closing')
    ,(@RACE_TAUREN, @CLASS_DRUID, 6247, 'Opening')
    ,(@RACE_TAUREN, @CLASS_DRUID, 6477, 'Opening')
    ,(@RACE_TAUREN, @CLASS_DRUID, 6478, 'Opening')
    ,(@RACE_TAUREN, @CLASS_DRUID, 6603, 'Attack')
    ,(@RACE_TAUREN, @CLASS_DRUID, 7266, 'Duel')
    ,(@RACE_TAUREN, @CLASS_DRUID, 7267, 'Grovel')
    ,(@RACE_TAUREN, @CLASS_DRUID, 7355, 'Stuck')
    ,(@RACE_TAUREN, @CLASS_DRUID, 8386, 'Attacking')
    ,(@RACE_TAUREN, @CLASS_DRUID, 9077, 'Leather')
    ,(@RACE_TAUREN, @CLASS_DRUID, 9078, 'Cloth')
    ,(@RACE_TAUREN, @CLASS_DRUID, 9125, 'Generic')
    ,(@RACE_TAUREN, @CLASS_DRUID, 20549, 'War Stomp')
    ,(@RACE_TAUREN, @CLASS_DRUID, 20550, 'Endurance')
    ,(@RACE_TAUREN, @CLASS_DRUID, 20551, 'Nature Resistance')
    ,(@RACE_TAUREN, @CLASS_DRUID, 20552, 'Cultivation')
    ,(@RACE_TAUREN, @CLASS_DRUID, 21651, 'Opening')
    ,(@RACE_TAUREN, @CLASS_DRUID, 21652, 'Closing')
    ,(@RACE_TAUREN, @CLASS_DRUID, 22027, 'Remove Insignia')
    ,(@RACE_TAUREN, @CLASS_DRUID, 22810, 'Opening - No Text')
    ,(@RACE_TAUREN, @CLASS_DRUID, 27764, 'Fetish')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_GNOME, @CLASS_WARRIOR, 78, 'Heroic Strike')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 81, 'Dodge')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 107, 'Block')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 198, 'One-Handed Maces')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 201, 'One-Handed Swords')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 203, 'Unarmed')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 204, 'Defense')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 668, 'Language Common')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 1180, 'Daggers')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 2382, 'Generic')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 2457, 'Battle Stance')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 2479, 'Honorless Target')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 3050, 'Detect')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 3365, 'Opening')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 5301, 'Defensive State (DND)')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 6233, 'Closing')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 6246, 'Closing')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 6247, 'Opening')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 6477, 'Opening')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 6478, 'Opening')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 6603, 'Attack')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 7266, 'Duel')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 7267, 'Grovel')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 7340, 'Language Gnomish')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 7355, 'Stuck')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 8386, 'Attacking')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 8737, 'Mail')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 9077, 'Leather')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 9078, 'Cloth')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 9116, 'Shield')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 9125, 'Generic')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 20589, 'Escape Artist')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 20591, 'Expansive Mind')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 20592, 'Arcane Resistance')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 20593, 'Engineering Specialization')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 21651, 'Opening')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 21652, 'Closing')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 22027, 'Remove Insignia')
    ,(@RACE_GNOME, @CLASS_WARRIOR, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_GNOME, @CLASS_ROGUE, 81, 'Dodge')
    ,(@RACE_GNOME, @CLASS_ROGUE, 203, 'Unarmed')
    ,(@RACE_GNOME, @CLASS_ROGUE, 204, 'Defense')
    ,(@RACE_GNOME, @CLASS_ROGUE, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_GNOME, @CLASS_ROGUE, 668, 'Language Common')
    ,(@RACE_GNOME, @CLASS_ROGUE, 1180, 'Daggers')
    ,(@RACE_GNOME, @CLASS_ROGUE, 1752, 'Sinister Strike')
    ,(@RACE_GNOME, @CLASS_ROGUE, 2098, 'Eviscerate')
    ,(@RACE_GNOME, @CLASS_ROGUE, 2382, 'Generic')
    ,(@RACE_GNOME, @CLASS_ROGUE, 2479, 'Honorless Target')
    ,(@RACE_GNOME, @CLASS_ROGUE, 2567, 'Thrown')
    ,(@RACE_GNOME, @CLASS_ROGUE, 2764, 'Throw')
    ,(@RACE_GNOME, @CLASS_ROGUE, 3050, 'Detect')
    ,(@RACE_GNOME, @CLASS_ROGUE, 3365, 'Opening')
    ,(@RACE_GNOME, @CLASS_ROGUE, 6233, 'Closing')
    ,(@RACE_GNOME, @CLASS_ROGUE, 6246, 'Closing')
    ,(@RACE_GNOME, @CLASS_ROGUE, 6247, 'Opening')
    ,(@RACE_GNOME, @CLASS_ROGUE, 6477, 'Opening')
    ,(@RACE_GNOME, @CLASS_ROGUE, 6478, 'Opening')
    ,(@RACE_GNOME, @CLASS_ROGUE, 6603, 'Attack')
    ,(@RACE_GNOME, @CLASS_ROGUE, 7266, 'Duel')
    ,(@RACE_GNOME, @CLASS_ROGUE, 7267, 'Grovel')
    ,(@RACE_GNOME, @CLASS_ROGUE, 7340, 'Language Gnomish')
    ,(@RACE_GNOME, @CLASS_ROGUE, 7355, 'Stuck')
    ,(@RACE_GNOME, @CLASS_ROGUE, 8386, 'Attacking')
    ,(@RACE_GNOME, @CLASS_ROGUE, 9077, 'Leather')
    ,(@RACE_GNOME, @CLASS_ROGUE, 9078, 'Cloth')
    ,(@RACE_GNOME, @CLASS_ROGUE, 9125, 'Generic')
    ,(@RACE_GNOME, @CLASS_ROGUE, 16092, 'Defensive State (DND)')
    ,(@RACE_GNOME, @CLASS_ROGUE, 20589, 'Escape Artist')
    ,(@RACE_GNOME, @CLASS_ROGUE, 20591, 'Expansive Mind')
    ,(@RACE_GNOME, @CLASS_ROGUE, 20592, 'Arcane Resistance')
    ,(@RACE_GNOME, @CLASS_ROGUE, 20593, 'Engineering Specialization')
    ,(@RACE_GNOME, @CLASS_ROGUE, 21184, 'Rogue Passive (DND)')
    ,(@RACE_GNOME, @CLASS_ROGUE, 21651, 'Opening')
    ,(@RACE_GNOME, @CLASS_ROGUE, 21652, 'Closing')
    ,(@RACE_GNOME, @CLASS_ROGUE, 22027, 'Remove Insignia')
    ,(@RACE_GNOME, @CLASS_ROGUE, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_GNOME, @CLASS_MAGE, 81, 'Dodge')
    ,(@RACE_GNOME, @CLASS_MAGE, 133, 'Fireball')
    ,(@RACE_GNOME, @CLASS_MAGE, 168, 'Frost Armor')
    ,(@RACE_GNOME, @CLASS_MAGE, 203, 'Unarmed')
    ,(@RACE_GNOME, @CLASS_MAGE, 204, 'Defense')
    ,(@RACE_GNOME, @CLASS_MAGE, 227, 'Staves')
    ,(@RACE_GNOME, @CLASS_MAGE, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_GNOME, @CLASS_MAGE, 668, 'Language Common')
    ,(@RACE_GNOME, @CLASS_MAGE, 2382, 'Generic')
    ,(@RACE_GNOME, @CLASS_MAGE, 2479, 'Honorless Target')
    ,(@RACE_GNOME, @CLASS_MAGE, 3050, 'Detect')
    ,(@RACE_GNOME, @CLASS_MAGE, 3365, 'Opening')
    ,(@RACE_GNOME, @CLASS_MAGE, 5009, 'Wands')
    ,(@RACE_GNOME, @CLASS_MAGE, 5019, 'Shoot')
    ,(@RACE_GNOME, @CLASS_MAGE, 6233, 'Closing')
    ,(@RACE_GNOME, @CLASS_MAGE, 6246, 'Closing')
    ,(@RACE_GNOME, @CLASS_MAGE, 6247, 'Opening')
    ,(@RACE_GNOME, @CLASS_MAGE, 6477, 'Opening')
    ,(@RACE_GNOME, @CLASS_MAGE, 6478, 'Opening')
    ,(@RACE_GNOME, @CLASS_MAGE, 6603, 'Attack')
    ,(@RACE_GNOME, @CLASS_MAGE, 7266, 'Duel')
    ,(@RACE_GNOME, @CLASS_MAGE, 7267, 'Grovel')
    ,(@RACE_GNOME, @CLASS_MAGE, 7340, 'Language Gnomish')
    ,(@RACE_GNOME, @CLASS_MAGE, 7355, 'Stuck')
    ,(@RACE_GNOME, @CLASS_MAGE, 8386, 'Attacking')
    ,(@RACE_GNOME, @CLASS_MAGE, 9078, 'Cloth')
    ,(@RACE_GNOME, @CLASS_MAGE, 9125, 'Generic')
    ,(@RACE_GNOME, @CLASS_MAGE, 20589, 'Escape Artist')
    ,(@RACE_GNOME, @CLASS_MAGE, 20591, 'Expansive Mind')
    ,(@RACE_GNOME, @CLASS_MAGE, 20592, 'Arcane Resistance')
    ,(@RACE_GNOME, @CLASS_MAGE, 20593, 'Engineering Specialization')
    ,(@RACE_GNOME, @CLASS_MAGE, 21651, 'Opening')
    ,(@RACE_GNOME, @CLASS_MAGE, 21652, 'Closing')
    ,(@RACE_GNOME, @CLASS_MAGE, 22027, 'Remove Insignia')
    ,(@RACE_GNOME, @CLASS_MAGE, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_GNOME, @CLASS_WARLOCK, 81, 'Dodge')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 203, 'Unarmed')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 204, 'Defense')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 668, 'Language Common')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 686, 'Shadow Bolt')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 687, 'Demon Skin')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 1180, 'Daggers')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 2382, 'Generic')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 2479, 'Honorless Target')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 3050, 'Detect')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 3365, 'Opening')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 5009, 'Wands')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 5019, 'Shoot')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 6233, 'Closing')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 6246, 'Closing')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 6247, 'Opening')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 6477, 'Opening')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 6478, 'Opening')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 6603, 'Attack')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 7266, 'Duel')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 7267, 'Grovel')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 7340, 'Language Gnomish')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 7355, 'Stuck')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 8386, 'Attacking')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 9078, 'Cloth')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 9125, 'Generic')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 20589, 'Escape Artist')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 20591, 'Expansive Mind')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 20592, 'Arcane Resistance')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 20593, 'Engineering Specialization')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 21651, 'Opening')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 21652, 'Closing')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 22027, 'Remove Insignia')
    ,(@RACE_GNOME, @CLASS_WARLOCK, 22810, 'Opening - No Text')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_TROLL, @CLASS_WARRIOR, 78, 'Heroic Strike')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 81, 'Dodge')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 107, 'Block')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 196, 'One-Handed Axes')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 203, 'Unarmed')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 204, 'Defense')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 669, 'Language Orcish')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 1180, 'Daggers')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 2382, 'Generic')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 2457, 'Battle Stance')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 2479, 'Honorless Target')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 2567, 'Thrown')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 2764, 'Throw')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 3050, 'Detect')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 3365, 'Opening')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 5301, 'Defensive State (DND)')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 6233, 'Closing')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 6246, 'Closing')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 6247, 'Opening')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 6477, 'Opening')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 6478, 'Opening')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 6603, 'Attack')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 7266, 'Duel')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 7267, 'Grovel')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 7341, 'Language Troll')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 7355, 'Stuck')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 8386, 'Attacking')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 8737, 'Mail')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 9077, 'Leather')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 9078, 'Cloth')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 9116, 'Shield')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 9125, 'Generic')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 20555, 'Regeneration')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 20557, 'Beast Slaying')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 20558, 'Throwing Specialization')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 21651, 'Opening')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 21652, 'Closing')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 22027, 'Remove Insignia')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 22810, 'Opening - No Text')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 26290, 'Bow Specialization')
    ,(@RACE_TROLL, @CLASS_WARRIOR, 26296, 'Berserking')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_TROLL, @CLASS_HUNTER, 75, 'Auto Shot')
    ,(@RACE_TROLL, @CLASS_HUNTER, 81, 'Dodge')
    ,(@RACE_TROLL, @CLASS_HUNTER, 196, 'One-Handed Axes')
    ,(@RACE_TROLL, @CLASS_HUNTER, 203, 'Unarmed')
    ,(@RACE_TROLL, @CLASS_HUNTER, 204, 'Defense')
    ,(@RACE_TROLL, @CLASS_HUNTER, 264, 'Bows')
    ,(@RACE_TROLL, @CLASS_HUNTER, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_TROLL, @CLASS_HUNTER, 669, 'Language Orcish')
    ,(@RACE_TROLL, @CLASS_HUNTER, 2382, 'Generic')
    ,(@RACE_TROLL, @CLASS_HUNTER, 2479, 'Honorless Target')
    ,(@RACE_TROLL, @CLASS_HUNTER, 2973, 'Raptor Strike')
    ,(@RACE_TROLL, @CLASS_HUNTER, 3050, 'Detect')
    ,(@RACE_TROLL, @CLASS_HUNTER, 3365, 'Opening')
    ,(@RACE_TROLL, @CLASS_HUNTER, 6233, 'Closing')
    ,(@RACE_TROLL, @CLASS_HUNTER, 6246, 'Closing')
    ,(@RACE_TROLL, @CLASS_HUNTER, 6247, 'Opening')
    ,(@RACE_TROLL, @CLASS_HUNTER, 6477, 'Opening')
    ,(@RACE_TROLL, @CLASS_HUNTER, 6478, 'Opening')
    ,(@RACE_TROLL, @CLASS_HUNTER, 6603, 'Attack')
    ,(@RACE_TROLL, @CLASS_HUNTER, 7266, 'Duel')
    ,(@RACE_TROLL, @CLASS_HUNTER, 7267, 'Grovel')
    ,(@RACE_TROLL, @CLASS_HUNTER, 7341, 'Language Troll')
    ,(@RACE_TROLL, @CLASS_HUNTER, 7355, 'Stuck')
    ,(@RACE_TROLL, @CLASS_HUNTER, 8386, 'Attacking')
    ,(@RACE_TROLL, @CLASS_HUNTER, 9077, 'Leather')
    ,(@RACE_TROLL, @CLASS_HUNTER, 9078, 'Cloth')
    ,(@RACE_TROLL, @CLASS_HUNTER, 9125, 'Generic')
    ,(@RACE_TROLL, @CLASS_HUNTER, 13358, 'Defensive State (DND)')
    ,(@RACE_TROLL, @CLASS_HUNTER, 20554, 'Berserking')
    ,(@RACE_TROLL, @CLASS_HUNTER, 20555, 'Regeneration')
    ,(@RACE_TROLL, @CLASS_HUNTER, 20557, 'Beast Slaying')
    ,(@RACE_TROLL, @CLASS_HUNTER, 20558, 'Throwing Specialization')
    ,(@RACE_TROLL, @CLASS_HUNTER, 21651, 'Opening')
    ,(@RACE_TROLL, @CLASS_HUNTER, 21652, 'Closing')
    ,(@RACE_TROLL, @CLASS_HUNTER, 22027, 'Remove Insignia')
    ,(@RACE_TROLL, @CLASS_HUNTER, 22810, 'Opening - No Text')
    ,(@RACE_TROLL, @CLASS_HUNTER, 24949, 'Defensive State 2 (DND)')
    ,(@RACE_TROLL, @CLASS_HUNTER, 26290, 'Bow Specialization')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_TROLL, @CLASS_ROGUE, 81, 'Dodge')
    ,(@RACE_TROLL, @CLASS_ROGUE, 203, 'Unarmed')
    ,(@RACE_TROLL, @CLASS_ROGUE, 204, 'Defense')
    ,(@RACE_TROLL, @CLASS_ROGUE, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_TROLL, @CLASS_ROGUE, 669, 'Language Orcish')
    ,(@RACE_TROLL, @CLASS_ROGUE, 1180, 'Daggers')
    ,(@RACE_TROLL, @CLASS_ROGUE, 1752, 'Sinister Strike')
    ,(@RACE_TROLL, @CLASS_ROGUE, 2098, 'Eviscerate')
    ,(@RACE_TROLL, @CLASS_ROGUE, 2382, 'Generic')
    ,(@RACE_TROLL, @CLASS_ROGUE, 2479, 'Honorless Target')
    ,(@RACE_TROLL, @CLASS_ROGUE, 2567, 'Thrown')
    ,(@RACE_TROLL, @CLASS_ROGUE, 2764, 'Throw')
    ,(@RACE_TROLL, @CLASS_ROGUE, 3050, 'Detect')
    ,(@RACE_TROLL, @CLASS_ROGUE, 3365, 'Opening')
    ,(@RACE_TROLL, @CLASS_ROGUE, 6233, 'Closing')
    ,(@RACE_TROLL, @CLASS_ROGUE, 6246, 'Closing')
    ,(@RACE_TROLL, @CLASS_ROGUE, 6247, 'Opening')
    ,(@RACE_TROLL, @CLASS_ROGUE, 6477, 'Opening')
    ,(@RACE_TROLL, @CLASS_ROGUE, 6478, 'Opening')
    ,(@RACE_TROLL, @CLASS_ROGUE, 6603, 'Attack')
    ,(@RACE_TROLL, @CLASS_ROGUE, 7266, 'Duel')
    ,(@RACE_TROLL, @CLASS_ROGUE, 7267, 'Grovel')
    ,(@RACE_TROLL, @CLASS_ROGUE, 7341, 'Language Troll')
    ,(@RACE_TROLL, @CLASS_ROGUE, 7355, 'Stuck')
    ,(@RACE_TROLL, @CLASS_ROGUE, 8386, 'Attacking')
    ,(@RACE_TROLL, @CLASS_ROGUE, 9077, 'Leather')
    ,(@RACE_TROLL, @CLASS_ROGUE, 9078, 'Cloth')
    ,(@RACE_TROLL, @CLASS_ROGUE, 9125, 'Generic')
    ,(@RACE_TROLL, @CLASS_ROGUE, 16092, 'Defensive State (DND)')
    ,(@RACE_TROLL, @CLASS_ROGUE, 20555, 'Regeneration')
    ,(@RACE_TROLL, @CLASS_ROGUE, 20557, 'Beast Slaying')
    ,(@RACE_TROLL, @CLASS_ROGUE, 20558, 'Throwing Specialization')
    ,(@RACE_TROLL, @CLASS_ROGUE, 21184, 'Rogue Passive (DND)')
    ,(@RACE_TROLL, @CLASS_ROGUE, 21651, 'Opening')
    ,(@RACE_TROLL, @CLASS_ROGUE, 21652, 'Closing')
    ,(@RACE_TROLL, @CLASS_ROGUE, 22027, 'Remove Insignia')
    ,(@RACE_TROLL, @CLASS_ROGUE, 22810, 'Opening - No Text')
    ,(@RACE_TROLL, @CLASS_ROGUE, 26290, 'Bow Specialization')
    ,(@RACE_TROLL, @CLASS_ROGUE, 26297, 'Berserking')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_TROLL, @CLASS_PRIEST, 81, 'Dodge')
    ,(@RACE_TROLL, @CLASS_PRIEST, 198, 'One-Handed Maces')
    ,(@RACE_TROLL, @CLASS_PRIEST, 203, 'Unarmed')
    ,(@RACE_TROLL, @CLASS_PRIEST, 204, 'Defense')
    ,(@RACE_TROLL, @CLASS_PRIEST, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_TROLL, @CLASS_PRIEST, 585, 'Smite')
    ,(@RACE_TROLL, @CLASS_PRIEST, 669, 'Language Orcish')
    ,(@RACE_TROLL, @CLASS_PRIEST, 2050, 'Lesser Heal')
    ,(@RACE_TROLL, @CLASS_PRIEST, 2382, 'Generic')
    ,(@RACE_TROLL, @CLASS_PRIEST, 2479, 'Honorless Target')
    ,(@RACE_TROLL, @CLASS_PRIEST, 3050, 'Detect')
    ,(@RACE_TROLL, @CLASS_PRIEST, 3365, 'Opening')
    ,(@RACE_TROLL, @CLASS_PRIEST, 5009, 'Wands')
    ,(@RACE_TROLL, @CLASS_PRIEST, 5019, 'Shoot')
    ,(@RACE_TROLL, @CLASS_PRIEST, 6233, 'Closing')
    ,(@RACE_TROLL, @CLASS_PRIEST, 6246, 'Closing')
    ,(@RACE_TROLL, @CLASS_PRIEST, 6247, 'Opening')
    ,(@RACE_TROLL, @CLASS_PRIEST, 6477, 'Opening')
    ,(@RACE_TROLL, @CLASS_PRIEST, 6478, 'Opening')
    ,(@RACE_TROLL, @CLASS_PRIEST, 6603, 'Attack')
    ,(@RACE_TROLL, @CLASS_PRIEST, 7266, 'Duel')
    ,(@RACE_TROLL, @CLASS_PRIEST, 7267, 'Grovel')
    ,(@RACE_TROLL, @CLASS_PRIEST, 7341, 'Language Troll')
    ,(@RACE_TROLL, @CLASS_PRIEST, 7355, 'Stuck')
    ,(@RACE_TROLL, @CLASS_PRIEST, 8386, 'Attacking')
    ,(@RACE_TROLL, @CLASS_PRIEST, 9078, 'Cloth')
    ,(@RACE_TROLL, @CLASS_PRIEST, 9125, 'Generic')
    ,(@RACE_TROLL, @CLASS_PRIEST, 20554, 'Berserking')
    ,(@RACE_TROLL, @CLASS_PRIEST, 20555, 'Regeneration')
    ,(@RACE_TROLL, @CLASS_PRIEST, 20557, 'Beast Slaying')
    ,(@RACE_TROLL, @CLASS_PRIEST, 20558, 'Throwing Specialization')
    ,(@RACE_TROLL, @CLASS_PRIEST, 21651, 'Opening')
    ,(@RACE_TROLL, @CLASS_PRIEST, 21652, 'Closing')
    ,(@RACE_TROLL, @CLASS_PRIEST, 22027, 'Remove Insignia')
    ,(@RACE_TROLL, @CLASS_PRIEST, 22810, 'Opening - No Text')
    ,(@RACE_TROLL, @CLASS_PRIEST, 26290, 'Bow Specialization')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_TROLL, @CLASS_SHAMAN, 81, 'Dodge')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 107, 'Block')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 198, 'One-Handed Maces')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 203, 'Unarmed')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 204, 'Defense')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 227, 'Staves')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 331, 'Healing Wave')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 403, 'Lightning Bolt')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 669, 'Language Orcish')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 2382, 'Generic')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 2479, 'Honorless Target')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 3050, 'Detect')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 3365, 'Opening')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 6233, 'Closing')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 6246, 'Closing')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 6247, 'Opening')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 6477, 'Opening')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 6478, 'Opening')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 6603, 'Attack')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 7266, 'Duel')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 7267, 'Grovel')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 7341, 'Language Troll')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 7355, 'Stuck')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 8386, 'Attacking')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 9077, 'Leather')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 9078, 'Cloth')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 9116, 'Shield')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 9125, 'Generic')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 20554, 'Berserking')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 20555, 'Regeneration')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 20557, 'Beast Slaying')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 20558, 'Throwing Specialization')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 21651, 'Opening')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 21652, 'Closing')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 22027, 'Remove Insignia')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 22810, 'Opening - No Text')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 26290, 'Bow Specialization')
    ,(@RACE_TROLL, @CLASS_SHAMAN, 27763, 'Totem')
;

INSERT INTO `playercreateinfo_spell`
    (`race`, `class`, `Spell`, `Note`)
VALUES
     (@RACE_TROLL, @CLASS_MAGE, 81, 'Dodge')
    ,(@RACE_TROLL, @CLASS_MAGE, 133, 'Fireball')
    ,(@RACE_TROLL, @CLASS_MAGE, 168, 'Frost Armor')
    ,(@RACE_TROLL, @CLASS_MAGE, 203, 'Unarmed')
    ,(@RACE_TROLL, @CLASS_MAGE, 204, 'Defense')
    ,(@RACE_TROLL, @CLASS_MAGE, 227, 'Staves')
    ,(@RACE_TROLL, @CLASS_MAGE, 522, 'SPELLDEFENSE (DND)')
    ,(@RACE_TROLL, @CLASS_MAGE, 669, 'Language Orcish')
    ,(@RACE_TROLL, @CLASS_MAGE, 2382, 'Generic')
    ,(@RACE_TROLL, @CLASS_MAGE, 2479, 'Honorless Target')
    ,(@RACE_TROLL, @CLASS_MAGE, 3050, 'Detect')
    ,(@RACE_TROLL, @CLASS_MAGE, 3365, 'Opening')
    ,(@RACE_TROLL, @CLASS_MAGE, 5009, 'Wands')
    ,(@RACE_TROLL, @CLASS_MAGE, 5019, 'Shoot')
    ,(@RACE_TROLL, @CLASS_MAGE, 6233, 'Closing')
    ,(@RACE_TROLL, @CLASS_MAGE, 6246, 'Closing')
    ,(@RACE_TROLL, @CLASS_MAGE, 6247, 'Opening')
    ,(@RACE_TROLL, @CLASS_MAGE, 6477, 'Opening')
    ,(@RACE_TROLL, @CLASS_MAGE, 6478, 'Opening')
    ,(@RACE_TROLL, @CLASS_MAGE, 6603, 'Attack')
    ,(@RACE_TROLL, @CLASS_MAGE, 7266, 'Duel')
    ,(@RACE_TROLL, @CLASS_MAGE, 7267, 'Grovel')
    ,(@RACE_TROLL, @CLASS_MAGE, 7341, 'Language Troll')
    ,(@RACE_TROLL, @CLASS_MAGE, 7355, 'Stuck')
    ,(@RACE_TROLL, @CLASS_MAGE, 8386, 'Attacking')
    ,(@RACE_TROLL, @CLASS_MAGE, 9078, 'Cloth')
    ,(@RACE_TROLL, @CLASS_MAGE, 9125, 'Generic')
    ,(@RACE_TROLL, @CLASS_MAGE, 20554, 'Berserking')
    ,(@RACE_TROLL, @CLASS_MAGE, 20555, 'Regeneration')
    ,(@RACE_TROLL, @CLASS_MAGE, 20557, 'Beast Slaying')
    ,(@RACE_TROLL, @CLASS_MAGE, 20558, 'Throwing Specialization')
    ,(@RACE_TROLL, @CLASS_MAGE, 21651, 'Opening')
    ,(@RACE_TROLL, @CLASS_MAGE, 21652, 'Closing')
    ,(@RACE_TROLL, @CLASS_MAGE, 22027, 'Remove Insignia')
    ,(@RACE_TROLL, @CLASS_MAGE, 22810, 'Opening - No Text')
    ,(@RACE_TROLL, @CLASS_MAGE, 26290, 'Bow Specialization')
;
